// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounting.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const groupBalanceSummary = `-- name: GroupBalanceSummary :many

SELECT
    asset,
    direction,
    COUNT(*)        AS tx_count,
    SUM(amount)::TEXT AS total_amount
FROM transactions
WHERE group_id = $1
  AND status = 'succeeded'
GROUP BY asset, direction
ORDER BY asset ASC, direction ASC
`

type GroupBalanceSummaryRow struct {
	Asset       string `json:"asset"`
	Direction   string `json:"direction"`
	TxCount     int64  `json:"tx_count"`
	TotalAmount string `json:"total_amount"`
}

// M9 accounting / statements queries.
//
// These are pure read aggregates over the existing transactions +
// onramp_orders tables. No new schema needed — we compute totals on the
// fly. Once volume justifies it, M9.2 can pre-materialize a
// monthly_statements rollup.
// Sum of succeeded outbound transfers BY asset for a wallet group across
// all rails. Plus inbound (received) totals for completeness. Caller
// subtracts to compute "net spent" in the dashboard if they want.
func (q *Queries) GroupBalanceSummary(ctx context.Context, groupID string) ([]GroupBalanceSummaryRow, error) {
	rows, err := q.db.Query(ctx, groupBalanceSummary, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GroupBalanceSummaryRow{}
	for rows.Next() {
		var i GroupBalanceSummaryRow
		if err := rows.Scan(
			&i.Asset,
			&i.Direction,
			&i.TxCount,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tenantMonthlyOnramp = `-- name: TenantMonthlyOnramp :many
SELECT
    fiat_currency,
    asset,
    COUNT(*)            AS order_count,
    SUM(fiat_amount)::TEXT   AS fiat_total,
    SUM(crypto_amount)::TEXT AS crypto_delivered
FROM onramp_orders
WHERE tenant_id = $1
  AND status = 'completed'
  AND created_at >= $2
  AND created_at <  $3
GROUP BY fiat_currency, asset
ORDER BY fiat_currency ASC, asset ASC
`

type TenantMonthlyOnrampParams struct {
	TenantID    string             `json:"tenant_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type TenantMonthlyOnrampRow struct {
	FiatCurrency    string `json:"fiat_currency"`
	Asset           string `json:"asset"`
	OrderCount      int64  `json:"order_count"`
	FiatTotal       string `json:"fiat_total"`
	CryptoDelivered string `json:"crypto_delivered"`
}

// Same window applied to onramp_orders. Fiat IN totals separately from
// crypto delivered so customers can see "you bought $X of USDC via N
// transactions" without joining tables.
func (q *Queries) TenantMonthlyOnramp(ctx context.Context, arg TenantMonthlyOnrampParams) ([]TenantMonthlyOnrampRow, error) {
	rows, err := q.db.Query(ctx, tenantMonthlyOnramp, arg.TenantID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantMonthlyOnrampRow{}
	for rows.Next() {
		var i TenantMonthlyOnrampRow
		if err := rows.Scan(
			&i.FiatCurrency,
			&i.Asset,
			&i.OrderCount,
			&i.FiatTotal,
			&i.CryptoDelivered,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tenantMonthlyStatement = `-- name: TenantMonthlyStatement :many
SELECT
    asset,
    direction,
    COUNT(*)        AS tx_count,
    SUM(amount)::TEXT AS total_amount
FROM transactions
WHERE tenant_id = $1
  AND status = 'succeeded'
  AND created_at >= $2
  AND created_at <  $3
GROUP BY asset, direction
ORDER BY asset ASC, direction ASC
`

type TenantMonthlyStatementParams struct {
	TenantID    string             `json:"tenant_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type TenantMonthlyStatementRow struct {
	Asset       string `json:"asset"`
	Direction   string `json:"direction"`
	TxCount     int64  `json:"tx_count"`
	TotalAmount string `json:"total_amount"`
}

// Per-(asset, direction) totals for a tenant in one month. The month
// boundary is computed by the caller; pass start (inclusive) and end
// (exclusive). Index hit: tenant_id is the most-selective FK on
// transactions, then created_at limits the scan further.
func (q *Queries) TenantMonthlyStatement(ctx context.Context, arg TenantMonthlyStatementParams) ([]TenantMonthlyStatementRow, error) {
	rows, err := q.db.Query(ctx, tenantMonthlyStatement, arg.TenantID, arg.CreatedAt, arg.CreatedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenantMonthlyStatementRow{}
	for rows.Next() {
		var i TenantMonthlyStatementRow
		if err := rows.Scan(
			&i.Asset,
			&i.Direction,
			&i.TxCount,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
