// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one

INSERT INTO api_keys (
    id, tenant_id, created_by, name, environment, key_prefix, key_hash
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, tenant_id, created_by, name, environment, key_prefix, key_hash, last_used_at, revoked_at, revoked_reason, created_at
`

type CreateAPIKeyParams struct {
	ID          string      `json:"id"`
	TenantID    string      `json:"tenant_id"`
	CreatedBy   pgtype.Text `json:"created_by"`
	Name        string      `json:"name"`
	Environment string      `json:"environment"`
	KeyPrefix   string      `json:"key_prefix"`
	KeyHash     []byte      `json:"key_hash"`
}

// API keys are the machine credentials customers attach to their HTTP
// requests (Bearer sk_test_… / sk_live_…). The raw secret is shown to the
// user exactly once at creation; from then on we look up by SHA-256 hash.
func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ID,
		arg.TenantID,
		arg.CreatedBy,
		arg.Name,
		arg.Environment,
		arg.KeyPrefix,
		arg.KeyHash,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CreatedBy,
		&i.Name,
		&i.Environment,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, tenant_id, created_by, name, environment, key_prefix, key_hash, last_used_at, revoked_at, revoked_reason, created_at FROM api_keys
WHERE key_hash = $1 AND revoked_at IS NULL
`

// Hot path on every API request. The index on key_hash makes this O(1).
// Returns the key only if it has not been revoked.
func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash []byte) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CreatedBy,
		&i.Name,
		&i.Environment,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, tenant_id, created_by, name, environment, key_prefix, key_hash, last_used_at, revoked_at, revoked_reason, created_at FROM api_keys
WHERE id = $1
`

func (q *Queries) GetAPIKeyByID(ctx context.Context, id string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByID, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CreatedBy,
		&i.Name,
		&i.Environment,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
	)
	return i, err
}

const listAPIKeysInTenant = `-- name: ListAPIKeysInTenant :many
SELECT id, tenant_id, created_by, name, environment, key_prefix, key_hash, last_used_at, revoked_at, revoked_reason, created_at FROM api_keys
WHERE tenant_id = $1
ORDER BY created_at DESC
`

// Dashboard listing. Includes revoked keys so customers can audit.
func (q *Queries) ListAPIKeysInTenant(ctx context.Context, tenantID string) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeysInTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.CreatedBy,
			&i.Name,
			&i.Environment,
			&i.KeyPrefix,
			&i.KeyHash,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.RevokedReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :one
UPDATE api_keys
SET revoked_at = NOW(),
    revoked_reason = $2
WHERE id = $1 AND revoked_at IS NULL
RETURNING id, tenant_id, created_by, name, environment, key_prefix, key_hash, last_used_at, revoked_at, revoked_reason, created_at
`

type RevokeAPIKeyParams struct {
	ID            string      `json:"id"`
	RevokedReason pgtype.Text `json:"revoked_reason"`
}

func (q *Queries) RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, revokeAPIKey, arg.ID, arg.RevokedReason)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.CreatedBy,
		&i.Name,
		&i.Environment,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.CreatedAt,
	)
	return i, err
}

const touchAPIKeyUsage = `-- name: TouchAPIKeyUsage :exec
UPDATE api_keys
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) TouchAPIKeyUsage(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchAPIKeyUsage, id)
	return err
}
