// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: limit_violations.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLimitViolation = `-- name: CreateLimitViolation :one

INSERT INTO limit_violations (
    tenant_id, policy_id, wallet_id, session_key_id, transaction_id,
    violation_type,
    attempted_amount, attempted_asset, attempted_recipient,
    limit_value, current_used,
    metadata
) VALUES (
    $1, $2, $3, $4, $5,
    $6,
    $7, $8, $9,
    $10, $11,
    $12
)
RETURNING id, tenant_id, policy_id, wallet_id, session_key_id, transaction_id, violation_type, attempted_amount, attempted_asset, attempted_recipient, limit_value, current_used, metadata, created_at
`

type CreateLimitViolationParams struct {
	TenantID           string         `json:"tenant_id"`
	PolicyID           pgtype.Text    `json:"policy_id"`
	WalletID           pgtype.Text    `json:"wallet_id"`
	SessionKeyID       pgtype.Text    `json:"session_key_id"`
	TransactionID      pgtype.Text    `json:"transaction_id"`
	ViolationType      string         `json:"violation_type"`
	AttemptedAmount    pgtype.Numeric `json:"attempted_amount"`
	AttemptedAsset     pgtype.Text    `json:"attempted_asset"`
	AttemptedRecipient pgtype.Text    `json:"attempted_recipient"`
	LimitValue         pgtype.Numeric `json:"limit_value"`
	CurrentUsed        pgtype.Numeric `json:"current_used"`
	Metadata           []byte         `json:"metadata"`
}

// Append-only audit log of every rejected attempt.
func (q *Queries) CreateLimitViolation(ctx context.Context, arg CreateLimitViolationParams) (LimitViolation, error) {
	row := q.db.QueryRow(ctx, createLimitViolation,
		arg.TenantID,
		arg.PolicyID,
		arg.WalletID,
		arg.SessionKeyID,
		arg.TransactionID,
		arg.ViolationType,
		arg.AttemptedAmount,
		arg.AttemptedAsset,
		arg.AttemptedRecipient,
		arg.LimitValue,
		arg.CurrentUsed,
		arg.Metadata,
	)
	var i LimitViolation
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.PolicyID,
		&i.WalletID,
		&i.SessionKeyID,
		&i.TransactionID,
		&i.ViolationType,
		&i.AttemptedAmount,
		&i.AttemptedAsset,
		&i.AttemptedRecipient,
		&i.LimitValue,
		&i.CurrentUsed,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listLimitViolationsByTenant = `-- name: ListLimitViolationsByTenant :many
SELECT id, tenant_id, policy_id, wallet_id, session_key_id, transaction_id, violation_type, attempted_amount, attempted_asset, attempted_recipient, limit_value, current_used, metadata, created_at FROM limit_violations
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListLimitViolationsByTenantParams struct {
	TenantID string `json:"tenant_id"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListLimitViolationsByTenant(ctx context.Context, arg ListLimitViolationsByTenantParams) ([]LimitViolation, error) {
	rows, err := q.db.Query(ctx, listLimitViolationsByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LimitViolation{}
	for rows.Next() {
		var i LimitViolation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PolicyID,
			&i.WalletID,
			&i.SessionKeyID,
			&i.TransactionID,
			&i.ViolationType,
			&i.AttemptedAmount,
			&i.AttemptedAsset,
			&i.AttemptedRecipient,
			&i.LimitValue,
			&i.CurrentUsed,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLimitViolationsByWallet = `-- name: ListLimitViolationsByWallet :many
SELECT id, tenant_id, policy_id, wallet_id, session_key_id, transaction_id, violation_type, attempted_amount, attempted_asset, attempted_recipient, limit_value, current_used, metadata, created_at FROM limit_violations
WHERE wallet_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListLimitViolationsByWalletParams struct {
	WalletID pgtype.Text `json:"wallet_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListLimitViolationsByWallet(ctx context.Context, arg ListLimitViolationsByWalletParams) ([]LimitViolation, error) {
	rows, err := q.db.Query(ctx, listLimitViolationsByWallet, arg.WalletID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LimitViolation{}
	for rows.Next() {
		var i LimitViolation
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.PolicyID,
			&i.WalletID,
			&i.SessionKeyID,
			&i.TransactionID,
			&i.ViolationType,
			&i.AttemptedAmount,
			&i.AttemptedAsset,
			&i.AttemptedRecipient,
			&i.LimitValue,
			&i.CurrentUsed,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
