// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: limit_policies.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLimitPolicy = `-- name: CreateLimitPolicy :one

INSERT INTO limit_policies (
    id, tenant_id, scope_type, scope_id,
    per_tx_amount, per_tx_asset,
    daily_amount, weekly_amount, monthly_amount, period_asset,
    timezone, reset_day_of_week, reset_day_of_month,
    allowed_recipients, denied_recipients,
    expires_at, enabled, metadata
) VALUES (
    $1, $2, $3, $4,
    $5, $6,
    $7, $8, $9, $10,
    $11, $12, $13,
    $14, $15,
    $16, $17, $18
)
RETURNING id, tenant_id, scope_type, scope_id, per_tx_amount, per_tx_asset, daily_amount, weekly_amount, monthly_amount, period_asset, timezone, reset_day_of_week, reset_day_of_month, allowed_recipients, denied_recipients, expires_at, enabled, metadata, created_at, updated_at
`

type CreateLimitPolicyParams struct {
	ID                string             `json:"id"`
	TenantID          string             `json:"tenant_id"`
	ScopeType         string             `json:"scope_type"`
	ScopeID           pgtype.Text        `json:"scope_id"`
	PerTxAmount       pgtype.Numeric     `json:"per_tx_amount"`
	PerTxAsset        pgtype.Text        `json:"per_tx_asset"`
	DailyAmount       pgtype.Numeric     `json:"daily_amount"`
	WeeklyAmount      pgtype.Numeric     `json:"weekly_amount"`
	MonthlyAmount     pgtype.Numeric     `json:"monthly_amount"`
	PeriodAsset       string             `json:"period_asset"`
	Timezone          string             `json:"timezone"`
	ResetDayOfWeek    int16              `json:"reset_day_of_week"`
	ResetDayOfMonth   int16              `json:"reset_day_of_month"`
	AllowedRecipients []byte             `json:"allowed_recipients"`
	DeniedRecipients  []byte             `json:"denied_recipients"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	Enabled           bool               `json:"enabled"`
	Metadata          []byte             `json:"metadata"`
}

// Declarative spending rules attached to a scope.
// scope_type ∈ {tenant_default, wallet_group, wallet, session_key}.
func (q *Queries) CreateLimitPolicy(ctx context.Context, arg CreateLimitPolicyParams) (LimitPolicy, error) {
	row := q.db.QueryRow(ctx, createLimitPolicy,
		arg.ID,
		arg.TenantID,
		arg.ScopeType,
		arg.ScopeID,
		arg.PerTxAmount,
		arg.PerTxAsset,
		arg.DailyAmount,
		arg.WeeklyAmount,
		arg.MonthlyAmount,
		arg.PeriodAsset,
		arg.Timezone,
		arg.ResetDayOfWeek,
		arg.ResetDayOfMonth,
		arg.AllowedRecipients,
		arg.DeniedRecipients,
		arg.ExpiresAt,
		arg.Enabled,
		arg.Metadata,
	)
	var i LimitPolicy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ScopeType,
		&i.ScopeID,
		&i.PerTxAmount,
		&i.PerTxAsset,
		&i.DailyAmount,
		&i.WeeklyAmount,
		&i.MonthlyAmount,
		&i.PeriodAsset,
		&i.Timezone,
		&i.ResetDayOfWeek,
		&i.ResetDayOfMonth,
		&i.AllowedRecipients,
		&i.DeniedRecipients,
		&i.ExpiresAt,
		&i.Enabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const disableLimitPolicy = `-- name: DisableLimitPolicy :one
UPDATE limit_policies
SET enabled = FALSE
WHERE id = $1
RETURNING id, tenant_id, scope_type, scope_id, per_tx_amount, per_tx_asset, daily_amount, weekly_amount, monthly_amount, period_asset, timezone, reset_day_of_week, reset_day_of_month, allowed_recipients, denied_recipients, expires_at, enabled, metadata, created_at, updated_at
`

// Soft-off: row stays so historical violations still reference it.
func (q *Queries) DisableLimitPolicy(ctx context.Context, id string) (LimitPolicy, error) {
	row := q.db.QueryRow(ctx, disableLimitPolicy, id)
	var i LimitPolicy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ScopeType,
		&i.ScopeID,
		&i.PerTxAmount,
		&i.PerTxAsset,
		&i.DailyAmount,
		&i.WeeklyAmount,
		&i.MonthlyAmount,
		&i.PeriodAsset,
		&i.Timezone,
		&i.ResetDayOfWeek,
		&i.ResetDayOfMonth,
		&i.AllowedRecipients,
		&i.DeniedRecipients,
		&i.ExpiresAt,
		&i.Enabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLimitPolicyByID = `-- name: GetLimitPolicyByID :one
SELECT id, tenant_id, scope_type, scope_id, per_tx_amount, per_tx_asset, daily_amount, weekly_amount, monthly_amount, period_asset, timezone, reset_day_of_week, reset_day_of_month, allowed_recipients, denied_recipients, expires_at, enabled, metadata, created_at, updated_at FROM limit_policies
WHERE id = $1
`

func (q *Queries) GetLimitPolicyByID(ctx context.Context, id string) (LimitPolicy, error) {
	row := q.db.QueryRow(ctx, getLimitPolicyByID, id)
	var i LimitPolicy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ScopeType,
		&i.ScopeID,
		&i.PerTxAmount,
		&i.PerTxAsset,
		&i.DailyAmount,
		&i.WeeklyAmount,
		&i.MonthlyAmount,
		&i.PeriodAsset,
		&i.Timezone,
		&i.ResetDayOfWeek,
		&i.ResetDayOfMonth,
		&i.AllowedRecipients,
		&i.DeniedRecipients,
		&i.ExpiresAt,
		&i.Enabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPolicyForScope = `-- name: GetPolicyForScope :one
SELECT id, tenant_id, scope_type, scope_id, per_tx_amount, per_tx_asset, daily_amount, weekly_amount, monthly_amount, period_asset, timezone, reset_day_of_week, reset_day_of_month, allowed_recipients, denied_recipients, expires_at, enabled, metadata, created_at, updated_at FROM limit_policies
WHERE tenant_id = $1
  AND scope_type = $2
  AND scope_id = $3
  AND enabled = TRUE
ORDER BY created_at DESC
LIMIT 1
`

type GetPolicyForScopeParams struct {
	TenantID  string      `json:"tenant_id"`
	ScopeType string      `json:"scope_type"`
	ScopeID   pgtype.Text `json:"scope_id"`
}

// Resolve the policy attached to a specific scope_id (wallet_group, wallet,
// or session_key). Returns the most recently-enabled one if duplicates
// exist (defensive — schema doesn't enforce uniqueness here).
func (q *Queries) GetPolicyForScope(ctx context.Context, arg GetPolicyForScopeParams) (LimitPolicy, error) {
	row := q.db.QueryRow(ctx, getPolicyForScope, arg.TenantID, arg.ScopeType, arg.ScopeID)
	var i LimitPolicy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ScopeType,
		&i.ScopeID,
		&i.PerTxAmount,
		&i.PerTxAsset,
		&i.DailyAmount,
		&i.WeeklyAmount,
		&i.MonthlyAmount,
		&i.PeriodAsset,
		&i.Timezone,
		&i.ResetDayOfWeek,
		&i.ResetDayOfMonth,
		&i.AllowedRecipients,
		&i.DeniedRecipients,
		&i.ExpiresAt,
		&i.Enabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantDefaultPolicy = `-- name: GetTenantDefaultPolicy :one
SELECT id, tenant_id, scope_type, scope_id, per_tx_amount, per_tx_asset, daily_amount, weekly_amount, monthly_amount, period_asset, timezone, reset_day_of_week, reset_day_of_month, allowed_recipients, denied_recipients, expires_at, enabled, metadata, created_at, updated_at FROM limit_policies
WHERE tenant_id = $1
  AND scope_type = 'tenant_default'
  AND enabled = TRUE
`

// The "fallback" policy applied when no more specific policy exists for a
// scope. The migration's partial-unique index guarantees at most one
// enabled tenant_default per tenant.
func (q *Queries) GetTenantDefaultPolicy(ctx context.Context, tenantID string) (LimitPolicy, error) {
	row := q.db.QueryRow(ctx, getTenantDefaultPolicy, tenantID)
	var i LimitPolicy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ScopeType,
		&i.ScopeID,
		&i.PerTxAmount,
		&i.PerTxAsset,
		&i.DailyAmount,
		&i.WeeklyAmount,
		&i.MonthlyAmount,
		&i.PeriodAsset,
		&i.Timezone,
		&i.ResetDayOfWeek,
		&i.ResetDayOfMonth,
		&i.AllowedRecipients,
		&i.DeniedRecipients,
		&i.ExpiresAt,
		&i.Enabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledPoliciesForTenant = `-- name: ListEnabledPoliciesForTenant :many
SELECT id, tenant_id, scope_type, scope_id, per_tx_amount, per_tx_asset, daily_amount, weekly_amount, monthly_amount, period_asset, timezone, reset_day_of_week, reset_day_of_month, allowed_recipients, denied_recipients, expires_at, enabled, metadata, created_at, updated_at FROM limit_policies
WHERE tenant_id = $1 AND enabled = TRUE
ORDER BY created_at DESC
`

func (q *Queries) ListEnabledPoliciesForTenant(ctx context.Context, tenantID string) ([]LimitPolicy, error) {
	rows, err := q.db.Query(ctx, listEnabledPoliciesForTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LimitPolicy{}
	for rows.Next() {
		var i LimitPolicy
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ScopeType,
			&i.ScopeID,
			&i.PerTxAmount,
			&i.PerTxAsset,
			&i.DailyAmount,
			&i.WeeklyAmount,
			&i.MonthlyAmount,
			&i.PeriodAsset,
			&i.Timezone,
			&i.ResetDayOfWeek,
			&i.ResetDayOfMonth,
			&i.AllowedRecipients,
			&i.DeniedRecipients,
			&i.ExpiresAt,
			&i.Enabled,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLimitPolicyCaps = `-- name: UpdateLimitPolicyCaps :one
UPDATE limit_policies
SET per_tx_amount   = $2,
    daily_amount    = $3,
    weekly_amount   = $4,
    monthly_amount  = $5
WHERE id = $1 AND enabled = TRUE
RETURNING id, tenant_id, scope_type, scope_id, per_tx_amount, per_tx_asset, daily_amount, weekly_amount, monthly_amount, period_asset, timezone, reset_day_of_week, reset_day_of_month, allowed_recipients, denied_recipients, expires_at, enabled, metadata, created_at, updated_at
`

type UpdateLimitPolicyCapsParams struct {
	ID            string         `json:"id"`
	PerTxAmount   pgtype.Numeric `json:"per_tx_amount"`
	DailyAmount   pgtype.Numeric `json:"daily_amount"`
	WeeklyAmount  pgtype.Numeric `json:"weekly_amount"`
	MonthlyAmount pgtype.Numeric `json:"monthly_amount"`
}

// Replace the spending caps. Recipient lists, scope, and other invariants
// are NOT mutable here — for those, customers create a new policy and
// disable the old one.
func (q *Queries) UpdateLimitPolicyCaps(ctx context.Context, arg UpdateLimitPolicyCapsParams) (LimitPolicy, error) {
	row := q.db.QueryRow(ctx, updateLimitPolicyCaps,
		arg.ID,
		arg.PerTxAmount,
		arg.DailyAmount,
		arg.WeeklyAmount,
		arg.MonthlyAmount,
	)
	var i LimitPolicy
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ScopeType,
		&i.ScopeID,
		&i.PerTxAmount,
		&i.PerTxAsset,
		&i.DailyAmount,
		&i.WeeklyAmount,
		&i.MonthlyAmount,
		&i.PeriodAsset,
		&i.Timezone,
		&i.ResetDayOfWeek,
		&i.ResetDayOfMonth,
		&i.AllowedRecipients,
		&i.DeniedRecipients,
		&i.ExpiresAt,
		&i.Enabled,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
