// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID            string             `json:"id"`
	TenantID      string             `json:"tenant_id"`
	CreatedBy     pgtype.Text        `json:"created_by"`
	Name          string             `json:"name"`
	Environment   string             `json:"environment"`
	KeyPrefix     string             `json:"key_prefix"`
	KeyHash       []byte             `json:"key_hash"`
	LastUsedAt    pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
	RevokedReason pgtype.Text        `json:"revoked_reason"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type LimitPolicy struct {
	ID                string             `json:"id"`
	TenantID          string             `json:"tenant_id"`
	ScopeType         string             `json:"scope_type"`
	ScopeID           pgtype.Text        `json:"scope_id"`
	PerTxAmount       pgtype.Numeric     `json:"per_tx_amount"`
	PerTxAsset        pgtype.Text        `json:"per_tx_asset"`
	DailyAmount       pgtype.Numeric     `json:"daily_amount"`
	WeeklyAmount      pgtype.Numeric     `json:"weekly_amount"`
	MonthlyAmount     pgtype.Numeric     `json:"monthly_amount"`
	PeriodAsset       string             `json:"period_asset"`
	Timezone          string             `json:"timezone"`
	ResetDayOfWeek    int16              `json:"reset_day_of_week"`
	ResetDayOfMonth   int16              `json:"reset_day_of_month"`
	AllowedRecipients []byte             `json:"allowed_recipients"`
	DeniedRecipients  []byte             `json:"denied_recipients"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	Enabled           bool               `json:"enabled"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type LimitViolation struct {
	ID                 int64              `json:"id"`
	TenantID           string             `json:"tenant_id"`
	PolicyID           pgtype.Text        `json:"policy_id"`
	WalletID           pgtype.Text        `json:"wallet_id"`
	SessionKeyID       pgtype.Text        `json:"session_key_id"`
	TransactionID      pgtype.Text        `json:"transaction_id"`
	ViolationType      string             `json:"violation_type"`
	AttemptedAmount    pgtype.Numeric     `json:"attempted_amount"`
	AttemptedAsset     pgtype.Text        `json:"attempted_asset"`
	AttemptedRecipient pgtype.Text        `json:"attempted_recipient"`
	LimitValue         pgtype.Numeric     `json:"limit_value"`
	CurrentUsed        pgtype.Numeric     `json:"current_used"`
	Metadata           []byte             `json:"metadata"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

type OnrampOrder struct {
	ID                string             `json:"id"`
	TenantID          string             `json:"tenant_id"`
	WalletID          string             `json:"wallet_id"`
	GroupID           string             `json:"group_id"`
	Provider          string             `json:"provider"`
	ProviderOrderID   pgtype.Text        `json:"provider_order_id"`
	CheckoutUrl       pgtype.Text        `json:"checkout_url"`
	FiatAmount        pgtype.Numeric     `json:"fiat_amount"`
	FiatCurrency      string             `json:"fiat_currency"`
	Asset             string             `json:"asset"`
	Chain             string             `json:"chain"`
	CryptoAmount      pgtype.Numeric     `json:"crypto_amount"`
	Status            string             `json:"status"`
	InitiatedByApikey pgtype.Text        `json:"initiated_by_apikey"`
	IdempotencyKey    pgtype.Text        `json:"idempotency_key"`
	ErrorCode         pgtype.Text        `json:"error_code"`
	ErrorMessage      pgtype.Text        `json:"error_message"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
}

type SessionKey struct {
	ID                string             `json:"id"`
	TenantID          string             `json:"tenant_id"`
	WalletID          string             `json:"wallet_id"`
	GroupID           string             `json:"group_id"`
	Name              string             `json:"name"`
	PublicAddress     string             `json:"public_address"`
	EncryptedPrivKey  []byte             `json:"encrypted_priv_key"`
	KeyVersion        int16              `json:"key_version"`
	PolicyID          pgtype.Text        `json:"policy_id"`
	RotationMode      string             `json:"rotation_mode"`
	RotationIntervalS int32              `json:"rotation_interval_s"`
	NextRotationAt    pgtype.Timestamptz `json:"next_rotation_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	Status            string             `json:"status"`
	RevokedReason     pgtype.Text        `json:"revoked_reason"`
	RevokedAt         pgtype.Timestamptz `json:"revoked_at"`
	RailNative        bool               `json:"rail_native"`
	OnChainTxHash     pgtype.Text        `json:"on_chain_tx_hash"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Tenant struct {
	ID           string             `json:"id"`
	Name         string             `json:"name"`
	PrimaryEmail string             `json:"primary_email"`
	Plan         string             `json:"plan"`
	Status       string             `json:"status"`
	Metadata     []byte             `json:"metadata"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Transaction struct {
	ID                string             `json:"id"`
	TenantID          string             `json:"tenant_id"`
	WalletID          string             `json:"wallet_id"`
	GroupID           string             `json:"group_id"`
	Rail              string             `json:"rail"`
	Chain             string             `json:"chain"`
	Direction         string             `json:"direction"`
	Counterparty      string             `json:"counterparty"`
	Amount            pgtype.Numeric     `json:"amount"`
	Asset             string             `json:"asset"`
	AmountUsd         pgtype.Numeric     `json:"amount_usd"`
	Status            string             `json:"status"`
	TxHash            pgtype.Text        `json:"tx_hash"`
	BlockNumber       pgtype.Int8        `json:"block_number"`
	ProviderTxID      pgtype.Text        `json:"provider_tx_id"`
	SessionKeyID      pgtype.Text        `json:"session_key_id"`
	InitiatedByUser   pgtype.Text        `json:"initiated_by_user"`
	InitiatedByApikey pgtype.Text        `json:"initiated_by_apikey"`
	IdempotencyKey    pgtype.Text        `json:"idempotency_key"`
	ErrorCode         pgtype.Text        `json:"error_code"`
	ErrorMessage      pgtype.Text        `json:"error_message"`
	Metadata          []byte             `json:"metadata"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	BroadcastAt       pgtype.Timestamptz `json:"broadcast_at"`
	ConfirmedAt       pgtype.Timestamptz `json:"confirmed_at"`
}

type UsageCounter struct {
	PolicyID   string             `json:"policy_id"`
	PeriodKey  string             `json:"period_key"`
	UsedAmount pgtype.Numeric     `json:"used_amount"`
	UsedAsset  string             `json:"used_asset"`
	LastTxID   pgtype.Text        `json:"last_tx_id"`
	FlushedAt  pgtype.Timestamptz `json:"flushed_at"`
}

type User struct {
	ID            string             `json:"id"`
	TenantID      string             `json:"tenant_id"`
	Email         string             `json:"email"`
	PasswordHash  string             `json:"password_hash"`
	Role          string             `json:"role"`
	EmailVerified bool               `json:"email_verified"`
	LastLoginAt   pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Wallet struct {
	ID                  string             `json:"id"`
	GroupID             string             `json:"group_id"`
	TenantID            string             `json:"tenant_id"`
	Rail                string             `json:"rail"`
	Chain               string             `json:"chain"`
	Address             string             `json:"address"`
	ProviderLocator     string             `json:"provider_locator"`
	Custody             string             `json:"custody"`
	EncryptedPrivateKey []byte             `json:"encrypted_private_key"`
	KeyVersion          pgtype.Int2        `json:"key_version"`
	Status              string             `json:"status"`
	Metadata            []byte             `json:"metadata"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type WalletGroup struct {
	ID            string             `json:"id"`
	TenantID      string             `json:"tenant_id"`
	OwnerType     string             `json:"owner_type"`
	OwnerRef      string             `json:"owner_ref"`
	ParentGroupID pgtype.Text        `json:"parent_group_id"`
	Custody       string             `json:"custody"`
	DisplayName   pgtype.Text        `json:"display_name"`
	Metadata      []byte             `json:"metadata"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type WebhookEndpoint struct {
	ID                  string             `json:"id"`
	TenantID            string             `json:"tenant_id"`
	Url                 string             `json:"url"`
	Secret              []byte             `json:"secret"`
	SecretVersion       int16              `json:"secret_version"`
	SubscribedEvents    []byte             `json:"subscribed_events"`
	Status              string             `json:"status"`
	Description         pgtype.Text        `json:"description"`
	LastSuccessAt       pgtype.Timestamptz `json:"last_success_at"`
	LastFailureAt       pgtype.Timestamptz `json:"last_failure_at"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	Metadata            []byte             `json:"metadata"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type WebhookEvent struct {
	ID                   string             `json:"id"`
	TenantID             string             `json:"tenant_id"`
	EndpointID           pgtype.Text        `json:"endpoint_id"`
	EventType            string             `json:"event_type"`
	EventData            []byte             `json:"event_data"`
	RelatedWalletID      pgtype.Text        `json:"related_wallet_id"`
	RelatedGroupID       pgtype.Text        `json:"related_group_id"`
	RelatedTransactionID pgtype.Text        `json:"related_transaction_id"`
	RelatedOnrampOrderID pgtype.Text        `json:"related_onramp_order_id"`
	RelatedSessionKeyID  pgtype.Text        `json:"related_session_key_id"`
	Status               string             `json:"status"`
	Attempts             int32              `json:"attempts"`
	NextAttemptAt        pgtype.Timestamptz `json:"next_attempt_at"`
	LastResponseCode     pgtype.Int4        `json:"last_response_code"`
	LastResponseBody     pgtype.Text        `json:"last_response_body"`
	LastError            pgtype.Text        `json:"last_error"`
	DeliveredAt          pgtype.Timestamptz `json:"delivered_at"`
	SignatureVersion     pgtype.Int2        `json:"signature_version"`
	Metadata             []byte             `json:"metadata"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}
