// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: onramp_orders.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOnrampOrder = `-- name: CreateOnrampOrder :one

INSERT INTO onramp_orders (
    id, tenant_id, wallet_id, group_id,
    provider, provider_order_id, checkout_url,
    fiat_amount, fiat_currency,
    asset, chain, crypto_amount,
    status, initiated_by_apikey, idempotency_key,
    expires_at, metadata
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9,
    $10, $11, $12,
    $13, $14, $15,
    $16, $17
)
RETURNING id, tenant_id, wallet_id, group_id, provider, provider_order_id, checkout_url, fiat_amount, fiat_currency, asset, chain, crypto_amount, status, initiated_by_apikey, idempotency_key, error_code, error_message, metadata, created_at, updated_at, expires_at, completed_at
`

type CreateOnrampOrderParams struct {
	ID                string             `json:"id"`
	TenantID          string             `json:"tenant_id"`
	WalletID          string             `json:"wallet_id"`
	GroupID           string             `json:"group_id"`
	Provider          string             `json:"provider"`
	ProviderOrderID   pgtype.Text        `json:"provider_order_id"`
	CheckoutUrl       pgtype.Text        `json:"checkout_url"`
	FiatAmount        string             `json:"fiat_amount"`
	FiatCurrency      string             `json:"fiat_currency"`
	Asset             string             `json:"asset"`
	Chain             string             `json:"chain"`
	CryptoAmount      pgtype.Numeric     `json:"crypto_amount"`
	Status            string             `json:"status"`
	InitiatedByApikey pgtype.Text        `json:"initiated_by_apikey"`
	IdempotencyKey    pgtype.Text        `json:"idempotency_key"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	Metadata          []byte             `json:"metadata"`
}

// Fiat → crypto purchases. The provider's hosted checkout URL is captured
// at creation; status advances via webhook updates from the provider.
func (q *Queries) CreateOnrampOrder(ctx context.Context, arg CreateOnrampOrderParams) (OnrampOrder, error) {
	row := q.db.QueryRow(ctx, createOnrampOrder,
		arg.ID,
		arg.TenantID,
		arg.WalletID,
		arg.GroupID,
		arg.Provider,
		arg.ProviderOrderID,
		arg.CheckoutUrl,
		arg.FiatAmount,
		arg.FiatCurrency,
		arg.Asset,
		arg.Chain,
		arg.CryptoAmount,
		arg.Status,
		arg.InitiatedByApikey,
		arg.IdempotencyKey,
		arg.ExpiresAt,
		arg.Metadata,
	)
	var i OnrampOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WalletID,
		&i.GroupID,
		&i.Provider,
		&i.ProviderOrderID,
		&i.CheckoutUrl,
		&i.FiatAmount,
		&i.FiatCurrency,
		&i.Asset,
		&i.Chain,
		&i.CryptoAmount,
		&i.Status,
		&i.InitiatedByApikey,
		&i.IdempotencyKey,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.CompletedAt,
	)
	return i, err
}

const getOnrampOrderByID = `-- name: GetOnrampOrderByID :one
SELECT id, tenant_id, wallet_id, group_id, provider, provider_order_id, checkout_url, fiat_amount, fiat_currency, asset, chain, crypto_amount, status, initiated_by_apikey, idempotency_key, error_code, error_message, metadata, created_at, updated_at, expires_at, completed_at FROM onramp_orders
WHERE id = $1
`

func (q *Queries) GetOnrampOrderByID(ctx context.Context, id string) (OnrampOrder, error) {
	row := q.db.QueryRow(ctx, getOnrampOrderByID, id)
	var i OnrampOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WalletID,
		&i.GroupID,
		&i.Provider,
		&i.ProviderOrderID,
		&i.CheckoutUrl,
		&i.FiatAmount,
		&i.FiatCurrency,
		&i.Asset,
		&i.Chain,
		&i.CryptoAmount,
		&i.Status,
		&i.InitiatedByApikey,
		&i.IdempotencyKey,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.CompletedAt,
	)
	return i, err
}

const getOnrampOrderByProviderID = `-- name: GetOnrampOrderByProviderID :one
SELECT id, tenant_id, wallet_id, group_id, provider, provider_order_id, checkout_url, fiat_amount, fiat_currency, asset, chain, crypto_amount, status, initiated_by_apikey, idempotency_key, error_code, error_message, metadata, created_at, updated_at, expires_at, completed_at FROM onramp_orders
WHERE provider = $1 AND provider_order_id = $2
`

type GetOnrampOrderByProviderIDParams struct {
	Provider        string      `json:"provider"`
	ProviderOrderID pgtype.Text `json:"provider_order_id"`
}

func (q *Queries) GetOnrampOrderByProviderID(ctx context.Context, arg GetOnrampOrderByProviderIDParams) (OnrampOrder, error) {
	row := q.db.QueryRow(ctx, getOnrampOrderByProviderID, arg.Provider, arg.ProviderOrderID)
	var i OnrampOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WalletID,
		&i.GroupID,
		&i.Provider,
		&i.ProviderOrderID,
		&i.CheckoutUrl,
		&i.FiatAmount,
		&i.FiatCurrency,
		&i.Asset,
		&i.Chain,
		&i.CryptoAmount,
		&i.Status,
		&i.InitiatedByApikey,
		&i.IdempotencyKey,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.CompletedAt,
	)
	return i, err
}

const listOnrampOrdersByGroup = `-- name: ListOnrampOrdersByGroup :many
SELECT id, tenant_id, wallet_id, group_id, provider, provider_order_id, checkout_url, fiat_amount, fiat_currency, asset, chain, crypto_amount, status, initiated_by_apikey, idempotency_key, error_code, error_message, metadata, created_at, updated_at, expires_at, completed_at FROM onramp_orders
WHERE group_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListOnrampOrdersByGroupParams struct {
	GroupID string `json:"group_id"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListOnrampOrdersByGroup(ctx context.Context, arg ListOnrampOrdersByGroupParams) ([]OnrampOrder, error) {
	rows, err := q.db.Query(ctx, listOnrampOrdersByGroup, arg.GroupID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OnrampOrder{}
	for rows.Next() {
		var i OnrampOrder
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WalletID,
			&i.GroupID,
			&i.Provider,
			&i.ProviderOrderID,
			&i.CheckoutUrl,
			&i.FiatAmount,
			&i.FiatCurrency,
			&i.Asset,
			&i.Chain,
			&i.CryptoAmount,
			&i.Status,
			&i.InitiatedByApikey,
			&i.IdempotencyKey,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOnrampOrdersByTenant = `-- name: ListOnrampOrdersByTenant :many
SELECT id, tenant_id, wallet_id, group_id, provider, provider_order_id, checkout_url, fiat_amount, fiat_currency, asset, chain, crypto_amount, status, initiated_by_apikey, idempotency_key, error_code, error_message, metadata, created_at, updated_at, expires_at, completed_at FROM onramp_orders
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListOnrampOrdersByTenantParams struct {
	TenantID string `json:"tenant_id"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListOnrampOrdersByTenant(ctx context.Context, arg ListOnrampOrdersByTenantParams) ([]OnrampOrder, error) {
	rows, err := q.db.Query(ctx, listOnrampOrdersByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OnrampOrder{}
	for rows.Next() {
		var i OnrampOrder
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WalletID,
			&i.GroupID,
			&i.Provider,
			&i.ProviderOrderID,
			&i.CheckoutUrl,
			&i.FiatAmount,
			&i.FiatCurrency,
			&i.Asset,
			&i.Chain,
			&i.CryptoAmount,
			&i.Status,
			&i.InitiatedByApikey,
			&i.IdempotencyKey,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExpiresAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOnrampOrderStatus = `-- name: UpdateOnrampOrderStatus :one
UPDATE onramp_orders
SET status        = $2,
    crypto_amount = COALESCE($3, crypto_amount),
    error_code    = COALESCE($4, error_code),
    error_message = COALESCE($5, error_message),
    completed_at  = CASE WHEN $2 IN ('completed', 'failed', 'expired')
                          AND completed_at IS NULL
                         THEN NOW() ELSE completed_at END
WHERE id = $1
RETURNING id, tenant_id, wallet_id, group_id, provider, provider_order_id, checkout_url, fiat_amount, fiat_currency, asset, chain, crypto_amount, status, initiated_by_apikey, idempotency_key, error_code, error_message, metadata, created_at, updated_at, expires_at, completed_at
`

type UpdateOnrampOrderStatusParams struct {
	ID           string         `json:"id"`
	Status       string         `json:"status"`
	CryptoAmount pgtype.Numeric `json:"crypto_amount"`
	ErrorCode    pgtype.Text    `json:"error_code"`
	ErrorMessage pgtype.Text    `json:"error_message"`
}

func (q *Queries) UpdateOnrampOrderStatus(ctx context.Context, arg UpdateOnrampOrderStatusParams) (OnrampOrder, error) {
	row := q.db.QueryRow(ctx, updateOnrampOrderStatus,
		arg.ID,
		arg.Status,
		arg.CryptoAmount,
		arg.ErrorCode,
		arg.ErrorMessage,
	)
	var i OnrampOrder
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WalletID,
		&i.GroupID,
		&i.Provider,
		&i.ProviderOrderID,
		&i.CheckoutUrl,
		&i.FiatAmount,
		&i.FiatCurrency,
		&i.Asset,
		&i.Chain,
		&i.CryptoAmount,
		&i.Status,
		&i.InitiatedByApikey,
		&i.IdempotencyKey,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
		&i.CompletedAt,
	)
	return i, err
}
