// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	// API keys are the machine credentials customers attach to their HTTP
	// requests (Bearer sk_test_… / sk_live_…). The raw secret is shown to the
	// user exactly once at creation; from then on we look up by SHA-256 hash.
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	// Tenants are ATARA-Pay's primary isolation unit.
	// Queries here are used by signup, billing, and the customer self-service
	// account page.
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	// Users are the humans logging into the dashboard. Always tenant-scoped.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Hot path on every API request. The index on key_hash makes this O(1).
	// Returns the key only if it has not been revoked.
	GetAPIKeyByHash(ctx context.Context, keyHash []byte) (ApiKey, error)
	GetAPIKeyByID(ctx context.Context, id string) (ApiKey, error)
	GetTenantByEmail(ctx context.Context, primaryEmail string) (Tenant, error)
	GetTenantByID(ctx context.Context, id string) (Tenant, error)
	// Some sign-in flows look up across tenants (e.g. user belongs to multiple
	// companies). Returns 0..n rows.
	GetUserByEmail(ctx context.Context, email string) ([]User, error)
	// Login flow: email + tenant_id is the unique pair.
	GetUserByEmailInTenant(ctx context.Context, arg GetUserByEmailInTenantParams) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	// Dashboard listing. Includes revoked keys so customers can audit.
	ListAPIKeysInTenant(ctx context.Context, tenantID string) ([]ApiKey, error)
	// Used by background sweepers and the admin console.
	ListActiveTenants(ctx context.Context, arg ListActiveTenantsParams) ([]Tenant, error)
	ListUsersInTenant(ctx context.Context, tenantID string) ([]User, error)
	MarkEmailVerified(ctx context.Context, id string) error
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (ApiKey, error)
	TouchAPIKeyUsage(ctx context.Context, id string) error
	TouchUserLogin(ctx context.Context, id string) error
	UpdateTenantPlan(ctx context.Context, arg UpdateTenantPlanParams) (Tenant, error)
	UpdateTenantStatus(ctx context.Context, arg UpdateTenantStatusParams) (Tenant, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
