// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// API keys are the machine credentials customers attach to their HTTP
	// requests (Bearer sk_test_… / sk_live_…). The raw secret is shown to the
	// user exactly once at creation; from then on we look up by SHA-256 hash.
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	// Declarative spending rules attached to a scope.
	// scope_type ∈ {tenant_default, wallet_group, wallet, session_key}.
	CreateLimitPolicy(ctx context.Context, arg CreateLimitPolicyParams) (LimitPolicy, error)
	// Append-only audit log of every rejected attempt.
	CreateLimitViolation(ctx context.Context, arg CreateLimitViolationParams) (LimitViolation, error)
	// Fiat → crypto purchases. The provider's hosted checkout URL is captured
	// at creation; status advances via webhook updates from the provider.
	CreateOnrampOrder(ctx context.Context, arg CreateOnrampOrderParams) (OnrampOrder, error)
	// Tenants are ATARA-Pay's primary isolation unit.
	// Queries here are used by signup, billing, and the customer self-service
	// account page.
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	// Money-movement audit table. Append-mostly: status fields advance via
	// UPDATE but rows are never deleted.
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	// Users are the humans logging into the dashboard. Always tenant-scoped.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// One wallet = one on-chain account on one rail (CrossMint / Tempo /
	// Loka-LN). Wallets belong to exactly one wallet_group via group_id.
	CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error)
	// Wallet groups bundle a logical "owner" (user / agent / merchant / treasury)
	// and the per-rail wallets that belong to it. One group typically holds
	// 2-3 wallets: one CrossMint, one Tempo, eventually one Loka-LN.
	CreateWalletGroup(ctx context.Context, arg CreateWalletGroupParams) (WalletGroup, error)
	// Soft-off: row stays so historical violations still reference it.
	DisableLimitPolicy(ctx context.Context, id string) (LimitPolicy, error)
	// Hot path on every API request. The index on key_hash makes this O(1).
	// Returns the key only if it has not been revoked.
	GetAPIKeyByHash(ctx context.Context, keyHash []byte) (ApiKey, error)
	GetAPIKeyByID(ctx context.Context, id string) (ApiKey, error)
	GetLimitPolicyByID(ctx context.Context, id string) (LimitPolicy, error)
	GetOnrampOrderByID(ctx context.Context, id string) (OnrampOrder, error)
	GetOnrampOrderByProviderID(ctx context.Context, arg GetOnrampOrderByProviderIDParams) (OnrampOrder, error)
	// Resolve the policy attached to a specific scope_id (wallet_group, wallet,
	// or session_key). Returns the most recently-enabled one if duplicates
	// exist (defensive — schema doesn't enforce uniqueness here).
	GetPolicyForScope(ctx context.Context, arg GetPolicyForScopeParams) (LimitPolicy, error)
	GetTenantByEmail(ctx context.Context, primaryEmail string) (Tenant, error)
	GetTenantByID(ctx context.Context, id string) (Tenant, error)
	// The "fallback" policy applied when no more specific policy exists for a
	// scope. The migration's partial-unique index guarantees at most one
	// enabled tenant_default per tenant.
	GetTenantDefaultPolicy(ctx context.Context, tenantID string) (LimitPolicy, error)
	GetTransactionByID(ctx context.Context, id string) (Transaction, error)
	GetTransactionByIdempotencyKey(ctx context.Context, arg GetTransactionByIdempotencyKeyParams) (Transaction, error)
	GetUsageCounter(ctx context.Context, arg GetUsageCounterParams) (UsageCounter, error)
	// Some sign-in flows look up across tenants (e.g. user belongs to multiple
	// companies). Returns 0..n rows.
	GetUserByEmail(ctx context.Context, email string) ([]User, error)
	// Login flow: email + tenant_id is the unique pair.
	GetUserByEmailInTenant(ctx context.Context, arg GetUserByEmailInTenantParams) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	// Reverse lookup for incoming-transfer webhooks. The address index is
	// partial on status='active' so deleted wallets don't clutter it.
	GetWalletByAddress(ctx context.Context, address string) (Wallet, error)
	// Hot path: when /v1/transactions or /v1/onramp resolves a group to a
	// specific rail's wallet, this query is what runs. The
	// (group_id, rail, chain) UNIQUE index makes it O(1).
	GetWalletByGroupAndRail(ctx context.Context, arg GetWalletByGroupAndRailParams) (Wallet, error)
	GetWalletByID(ctx context.Context, id string) (Wallet, error)
	// Reverse lookup for provider webhooks that hand us a CrossMint cm_xxx
	// or similar opaque id.
	GetWalletByProviderLocator(ctx context.Context, arg GetWalletByProviderLocatorParams) (Wallet, error)
	GetWalletGroupByID(ctx context.Context, id string) (WalletGroup, error)
	// The lookup the dual-create endpoint needs to honor idempotency: if the
	// customer POSTs /v1/wallet-groups twice with the same owner_ref, we
	// return the existing group instead of failing.
	GetWalletGroupByOwnerRef(ctx context.Context, arg GetWalletGroupByOwnerRefParams) (WalletGroup, error)
	// Dashboard listing. Includes revoked keys so customers can audit.
	ListAPIKeysInTenant(ctx context.Context, tenantID string) ([]ApiKey, error)
	// Used by background sweepers and the admin console.
	ListActiveTenants(ctx context.Context, arg ListActiveTenantsParams) ([]Tenant, error)
	// All agent groups belonging to a particular user group (parent → child).
	// Used by the dashboard to show "Alice's agents" under Alice's user group.
	ListAgentGroupsForParent(ctx context.Context, parentGroupID pgtype.Text) ([]WalletGroup, error)
	ListEnabledPoliciesForTenant(ctx context.Context, tenantID string) ([]LimitPolicy, error)
	ListLimitViolationsByTenant(ctx context.Context, arg ListLimitViolationsByTenantParams) ([]LimitViolation, error)
	ListLimitViolationsByWallet(ctx context.Context, arg ListLimitViolationsByWalletParams) ([]LimitViolation, error)
	ListOnrampOrdersByGroup(ctx context.Context, arg ListOnrampOrdersByGroupParams) ([]OnrampOrder, error)
	ListOnrampOrdersByTenant(ctx context.Context, arg ListOnrampOrdersByTenantParams) ([]OnrampOrder, error)
	ListTransactionsByGroup(ctx context.Context, arg ListTransactionsByGroupParams) ([]Transaction, error)
	ListTransactionsByTenant(ctx context.Context, arg ListTransactionsByTenantParams) ([]Transaction, error)
	ListTransactionsByWallet(ctx context.Context, arg ListTransactionsByWalletParams) ([]Transaction, error)
	// Used by the dashboard "remaining today / this week / this month" view.
	ListUsageCountersForPolicy(ctx context.Context, policyID string) ([]UsageCounter, error)
	ListUsersInTenant(ctx context.Context, tenantID string) ([]User, error)
	// Dashboard listing. Filter by owner_type (e.g. only show agents) is
	// handled at the application layer.
	ListWalletGroupsInTenant(ctx context.Context, arg ListWalletGroupsInTenantParams) ([]WalletGroup, error)
	// Returns every wallet of a group, ordered so CrossMint comes before Tempo
	// before Loka-LN — gives the dashboard a stable display order without
	// per-rail logic in the frontend.
	ListWalletsByGroup(ctx context.Context, groupID string) ([]Wallet, error)
	MarkEmailVerified(ctx context.Context, id string) error
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (ApiKey, error)
	// Soft delete. The row stays so audit / reporting can still find it.
	// Cascades to the wallets table via the foreign key (which then go
	// status='deleted' through the same touch trigger).
	SoftDeleteWalletGroup(ctx context.Context, id string) error
	TouchAPIKeyUsage(ctx context.Context, id string) error
	TouchUserLogin(ctx context.Context, id string) error
	// Replace the spending caps. Recipient lists, scope, and other invariants
	// are NOT mutable here — for those, customers create a new policy and
	// disable the old one.
	UpdateLimitPolicyCaps(ctx context.Context, arg UpdateLimitPolicyCapsParams) (LimitPolicy, error)
	UpdateOnrampOrderStatus(ctx context.Context, arg UpdateOnrampOrderStatusParams) (OnrampOrder, error)
	UpdateTenantPlan(ctx context.Context, arg UpdateTenantPlanParams) (Tenant, error)
	UpdateTenantStatus(ctx context.Context, arg UpdateTenantStatusParams) (Tenant, error)
	UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (Transaction, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	// Used by the keystore when the master key rotates. We keep encrypted_
	// private_key + key_version together to avoid ever decrypting with the
	// wrong master generation.
	UpdateWalletEncryptedKey(ctx context.Context, arg UpdateWalletEncryptedKeyParams) error
	UpdateWalletGroupDisplayName(ctx context.Context, arg UpdateWalletGroupDisplayNameParams) (WalletGroup, error)
	UpdateWalletStatus(ctx context.Context, arg UpdateWalletStatusParams) (Wallet, error)
	// Durable mirror of the hot-path Redis counters. Redis is the canonical
	// source for live values; PG is the persisted copy flushed periodically
	// so audits, reports, and Redis-outage recovery work.
	//
	// period_key formats:
	//   daily:2026-05-20
	//   weekly:2026-W21
	//   monthly:2026-05
	// Used both by the periodic Redis → PG flush and as a fallback path when
	// Redis is unavailable. ON CONFLICT updates used_amount monotonically;
	// we never go backwards (Redis is authoritative for live values).
	UpsertUsageCounter(ctx context.Context, arg UpsertUsageCounterParams) (UsageCounter, error)
}

var _ Querier = (*Queries)(nil)
