// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// API keys are the machine credentials customers attach to their HTTP
	// requests (Bearer sk_test_… / sk_live_…). The raw secret is shown to the
	// user exactly once at creation; from then on we look up by SHA-256 hash.
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	// Declarative spending rules attached to a scope.
	// scope_type ∈ {tenant_default, wallet_group, wallet, session_key}.
	CreateLimitPolicy(ctx context.Context, arg CreateLimitPolicyParams) (LimitPolicy, error)
	// Append-only audit log of every rejected attempt.
	CreateLimitViolation(ctx context.Context, arg CreateLimitViolationParams) (LimitViolation, error)
	// Fiat → crypto purchases. The provider's hosted checkout URL is captured
	// at creation; status advances via webhook updates from the provider.
	CreateOnrampOrder(ctx context.Context, arg CreateOnrampOrderParams) (OnrampOrder, error)
	// Session keys: delegated signers attached to a wallet, each carrying its
	// own limit_policy and rotation schedule. The DB invariants are enforced
	// by the schema (see migration 000004); these queries are kept minimal so
	// the orchestration service can compose them in transactions.
	CreateSessionKey(ctx context.Context, arg CreateSessionKeyParams) (SessionKey, error)
	// Tenants are ATARA-Pay's primary isolation unit.
	// Queries here are used by signup, billing, and the customer self-service
	// account page.
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	// Money-movement audit table. Append-mostly: status fields advance via
	// UPDATE but rows are never deleted.
	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	// Users are the humans logging into the dashboard. Always tenant-scoped.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// One wallet = one on-chain account on one rail (CrossMint / Tempo /
	// Loka-LN). Wallets belong to exactly one wallet_group via group_id.
	CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error)
	// Wallet groups bundle a logical "owner" (user / agent / merchant / treasury)
	// and the per-rail wallets that belong to it. One group typically holds
	// 2-3 wallets: one CrossMint, one Tempo, eventually one Loka-LN.
	CreateWalletGroup(ctx context.Context, arg CreateWalletGroupParams) (WalletGroup, error)
	// Customer-registered webhook destinations. The HMAC secret is opaque
	// bytes; the application minted it and showed it once at creation.
	CreateWebhookEndpoint(ctx context.Context, arg CreateWebhookEndpointParams) (WebhookEndpoint, error)
	// Per-(domain-event, subscribed-endpoint) delivery records. The delivery
	// worker iterates pending/failed rows whose next_attempt_at has arrived.
	CreateWebhookEvent(ctx context.Context, arg CreateWebhookEventParams) (WebhookEvent, error)
	// Soft delete via status='deleted' so historical webhook_events still
	// resolve their endpoint_id back to a row.
	DeleteWebhookEndpoint(ctx context.Context, id string) error
	// Soft-off: row stays so historical violations still reference it.
	DisableLimitPolicy(ctx context.Context, id string) (LimitPolicy, error)
	// Hot path on every API request. The index on key_hash makes this O(1).
	// Returns the key only if it has not been revoked.
	GetAPIKeyByHash(ctx context.Context, keyHash []byte) (ApiKey, error)
	GetAPIKeyByID(ctx context.Context, id string) (ApiKey, error)
	// Hot path: when a transaction is signed with a session key, we identify
	// the signer by its 0x-address and need the row's encrypted_priv_key +
	// policy_id + status in one lookup. The partial index on (public_address)
	// WHERE status='active' makes this O(1).
	GetActiveSessionKeyByPublicAddress(ctx context.Context, publicAddress string) (SessionKey, error)
	GetLimitPolicyByID(ctx context.Context, id string) (LimitPolicy, error)
	GetOnrampOrderByID(ctx context.Context, id string) (OnrampOrder, error)
	GetOnrampOrderByProviderID(ctx context.Context, arg GetOnrampOrderByProviderIDParams) (OnrampOrder, error)
	// Resolve the policy attached to a specific scope_id (wallet_group, wallet,
	// or session_key). Returns the most recently-enabled one if duplicates
	// exist (defensive — schema doesn't enforce uniqueness here).
	GetPolicyForScope(ctx context.Context, arg GetPolicyForScopeParams) (LimitPolicy, error)
	GetSessionKeyByID(ctx context.Context, id string) (SessionKey, error)
	GetTenantByEmail(ctx context.Context, primaryEmail string) (Tenant, error)
	GetTenantByID(ctx context.Context, id string) (Tenant, error)
	// The "fallback" policy applied when no more specific policy exists for a
	// scope. The migration's partial-unique index guarantees at most one
	// enabled tenant_default per tenant.
	GetTenantDefaultPolicy(ctx context.Context, tenantID string) (LimitPolicy, error)
	GetTransactionByID(ctx context.Context, id string) (Transaction, error)
	GetTransactionByIdempotencyKey(ctx context.Context, arg GetTransactionByIdempotencyKeyParams) (Transaction, error)
	GetUsageCounter(ctx context.Context, arg GetUsageCounterParams) (UsageCounter, error)
	// Some sign-in flows look up across tenants (e.g. user belongs to multiple
	// companies). Returns 0..n rows.
	GetUserByEmail(ctx context.Context, email string) ([]User, error)
	// Login flow: email + tenant_id is the unique pair.
	GetUserByEmailInTenant(ctx context.Context, arg GetUserByEmailInTenantParams) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	// Reverse lookup for incoming-transfer webhooks. The address index is
	// partial on status='active' so deleted wallets don't clutter it.
	GetWalletByAddress(ctx context.Context, address string) (Wallet, error)
	// Hot path: when /v1/transactions or /v1/onramp resolves a group to a
	// specific rail's wallet, this query is what runs. The
	// (group_id, rail, chain) UNIQUE index makes it O(1).
	GetWalletByGroupAndRail(ctx context.Context, arg GetWalletByGroupAndRailParams) (Wallet, error)
	GetWalletByID(ctx context.Context, id string) (Wallet, error)
	// Reverse lookup for provider webhooks that hand us a CrossMint cm_xxx
	// or similar opaque id.
	GetWalletByProviderLocator(ctx context.Context, arg GetWalletByProviderLocatorParams) (Wallet, error)
	GetWalletGroupByID(ctx context.Context, id string) (WalletGroup, error)
	// The lookup the dual-create endpoint needs to honor idempotency: if the
	// customer POSTs /v1/wallet-groups twice with the same owner_ref, we
	// return the existing group instead of failing.
	GetWalletGroupByOwnerRef(ctx context.Context, arg GetWalletGroupByOwnerRefParams) (WalletGroup, error)
	GetWebhookEndpointByID(ctx context.Context, id string) (WebhookEndpoint, error)
	GetWebhookEventByID(ctx context.Context, id string) (WebhookEvent, error)
	// Dashboard listing. Includes revoked keys so customers can audit.
	ListAPIKeysInTenant(ctx context.Context, tenantID string) ([]ApiKey, error)
	// The publisher fans out one domain event to every active subscriber of
	// this tenant. Filtering on subscribed_events happens in app code (JSONB
	// containment) so each event is matched against the array.
	ListActiveEndpointsForTenant(ctx context.Context, tenantID string) ([]WebhookEndpoint, error)
	// Used by background sweepers and the admin console.
	ListActiveTenants(ctx context.Context, arg ListActiveTenantsParams) ([]Tenant, error)
	// All agent groups belonging to a particular user group (parent → child).
	// Used by the dashboard to show "Alice's agents" under Alice's user group.
	ListAgentGroupsForParent(ctx context.Context, parentGroupID pgtype.Text) ([]WalletGroup, error)
	// Hot path for the delivery worker. Hits the partial index on
	// next_attempt_at WHERE status IN ('pending','failed'). LIMIT enforces
	// per-tick budget.
	ListDueWebhookEvents(ctx context.Context, arg ListDueWebhookEventsParams) ([]WebhookEvent, error)
	ListEnabledPoliciesForTenant(ctx context.Context, tenantID string) ([]LimitPolicy, error)
	// Sweep: keys whose expires_at has passed but status still says
	// active/rotating. The cron flips them to 'expired'.
	ListExpiredSessionKeys(ctx context.Context, arg ListExpiredSessionKeysParams) ([]SessionKey, error)
	ListLimitViolationsByTenant(ctx context.Context, arg ListLimitViolationsByTenantParams) ([]LimitViolation, error)
	ListLimitViolationsByWallet(ctx context.Context, arg ListLimitViolationsByWalletParams) ([]LimitViolation, error)
	ListOnrampOrdersByGroup(ctx context.Context, arg ListOnrampOrdersByGroupParams) ([]OnrampOrder, error)
	ListOnrampOrdersByTenant(ctx context.Context, arg ListOnrampOrdersByTenantParams) ([]OnrampOrder, error)
	// Background worker scans this every cycle. The partial index on
	// next_rotation_at filtered to (rotation_mode='auto_rotate' AND
	// status='active') keeps the scan tight regardless of total population.
	ListSessionKeysDueForRotation(ctx context.Context, arg ListSessionKeysDueForRotationParams) ([]SessionKey, error)
	ListSessionKeysForTenant(ctx context.Context, arg ListSessionKeysForTenantParams) ([]SessionKey, error)
	// Dashboard listing. Includes revoked / expired so customers can audit
	// history; the UI strikes through inactive rows.
	ListSessionKeysForWallet(ctx context.Context, arg ListSessionKeysForWalletParams) ([]SessionKey, error)
	ListTransactionsByGroup(ctx context.Context, arg ListTransactionsByGroupParams) ([]Transaction, error)
	ListTransactionsByTenant(ctx context.Context, arg ListTransactionsByTenantParams) ([]Transaction, error)
	ListTransactionsByWallet(ctx context.Context, arg ListTransactionsByWalletParams) ([]Transaction, error)
	// Used by the dashboard "remaining today / this week / this month" view.
	ListUsageCountersForPolicy(ctx context.Context, policyID string) ([]UsageCounter, error)
	ListUsersInTenant(ctx context.Context, tenantID string) ([]User, error)
	// Dashboard listing. Filter by owner_type (e.g. only show agents) is
	// handled at the application layer.
	ListWalletGroupsInTenant(ctx context.Context, arg ListWalletGroupsInTenantParams) ([]WalletGroup, error)
	// Returns every wallet of a group, ordered so CrossMint comes before Tempo
	// before Loka-LN — gives the dashboard a stable display order without
	// per-rail logic in the frontend.
	ListWalletsByGroup(ctx context.Context, groupID string) ([]Wallet, error)
	ListWebhookEndpointsForTenant(ctx context.Context, arg ListWebhookEndpointsForTenantParams) ([]WebhookEndpoint, error)
	ListWebhookEventsForEndpoint(ctx context.Context, arg ListWebhookEventsForEndpointParams) ([]WebhookEvent, error)
	ListWebhookEventsForTenant(ctx context.Context, arg ListWebhookEventsForTenantParams) ([]WebhookEvent, error)
	MarkEmailVerified(ctx context.Context, id string) error
	// Terminal state after the retry budget is exhausted.
	MarkWebhookEventDead(ctx context.Context, id string) error
	MarkWebhookEventDelivered(ctx context.Context, arg MarkWebhookEventDeliveredParams) (WebhookEvent, error)
	// Take ownership: flip status to 'delivering' so a parallel worker
	// doesn't pick the same row up. Returns the row only when the transition
	// succeeded — concurrent workers see no rows and skip.
	MarkWebhookEventDelivering(ctx context.Context, id string) (WebhookEvent, error)
	// One failed delivery attempt. Bumps attempts + schedules next retry.
	// The worker computes next_attempt_at via exponential backoff and
	// passes it in.
	MarkWebhookEventFailed(ctx context.Context, arg MarkWebhookEventFailedParams) (WebhookEvent, error)
	PauseWebhookEndpoint(ctx context.Context, id string) error
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (ApiKey, error)
	// Idempotent at the SQL layer via the WHERE status='active' guard —
	// repeat revokes don't overwrite the original revoked_at.
	RevokeSessionKey(ctx context.Context, arg RevokeSessionKeyParams) (SessionKey, error)
	// Bumps the secret and its version atomically. Deliveries already in
	// flight keep using the prior version via webhook_events.signature_version.
	RotateWebhookEndpointSecret(ctx context.Context, arg RotateWebhookEndpointSecretParams) (WebhookEndpoint, error)
	// Soft delete. The row stays so audit / reporting can still find it.
	// Cascades to the wallets table via the foreign key (which then go
	// status='deleted' through the same touch trigger).
	SoftDeleteWalletGroup(ctx context.Context, id string) error
	TouchAPIKeyUsage(ctx context.Context, id string) error
	TouchUserLogin(ctx context.Context, id string) error
	// Bumps the failure counter and returns the new value so the worker can
	// decide whether to auto-pause the endpoint (e.g. after 30 in a row).
	TouchWebhookEndpointFailure(ctx context.Context, id string) (int32, error)
	TouchWebhookEndpointSuccess(ctx context.Context, id string) error
	// Replace the spending caps. Recipient lists, scope, and other invariants
	// are NOT mutable here — for those, customers create a new policy and
	// disable the old one.
	UpdateLimitPolicyCaps(ctx context.Context, arg UpdateLimitPolicyCapsParams) (LimitPolicy, error)
	UpdateOnrampOrderStatus(ctx context.Context, arg UpdateOnrampOrderStatusParams) (OnrampOrder, error)
	// Atomically reset the auto-rotation cursor after the worker hands out a
	// replacement key.
	UpdateSessionKeyNextRotation(ctx context.Context, arg UpdateSessionKeyNextRotationParams) error
	UpdateSessionKeyStatus(ctx context.Context, arg UpdateSessionKeyStatusParams) (SessionKey, error)
	UpdateTenantPlan(ctx context.Context, arg UpdateTenantPlanParams) (Tenant, error)
	UpdateTenantStatus(ctx context.Context, arg UpdateTenantStatusParams) (Tenant, error)
	UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (Transaction, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	// Used by the keystore when the master key rotates. We keep encrypted_
	// private_key + key_version together to avoid ever decrypting with the
	// wrong master generation.
	UpdateWalletEncryptedKey(ctx context.Context, arg UpdateWalletEncryptedKeyParams) error
	UpdateWalletGroupDisplayName(ctx context.Context, arg UpdateWalletGroupDisplayNameParams) (WalletGroup, error)
	UpdateWalletStatus(ctx context.Context, arg UpdateWalletStatusParams) (Wallet, error)
	// Mutable surface: URL, subscribed_events, description, status. The
	// secret is rotated via RotateWebhookEndpointSecret only — keeping the
	// updates separate so a tenant can't accidentally race a URL change with
	// a secret rotation in the same call.
	UpdateWebhookEndpoint(ctx context.Context, arg UpdateWebhookEndpointParams) (WebhookEndpoint, error)
	// Durable mirror of the hot-path Redis counters. Redis is the canonical
	// source for live values; PG is the persisted copy flushed periodically
	// so audits, reports, and Redis-outage recovery work.
	//
	// period_key formats:
	//   daily:2026-05-20
	//   weekly:2026-W21
	//   monthly:2026-05
	// Used both by the periodic Redis → PG flush and as a fallback path when
	// Redis is unavailable. ON CONFLICT updates used_amount monotonically;
	// we never go backwards (Redis is authoritative for live values).
	UpsertUsageCounter(ctx context.Context, arg UpsertUsageCounterParams) (UsageCounter, error)
}

var _ Querier = (*Queries)(nil)
