// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session_keys.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSessionKey = `-- name: CreateSessionKey :one

INSERT INTO session_keys (
    id, tenant_id, wallet_id, group_id, name,
    public_address, encrypted_priv_key, key_version,
    policy_id,
    rotation_mode, rotation_interval_s, next_rotation_at,
    expires_at, status,
    rail_native, on_chain_tx_hash,
    metadata
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9,
    $10, $11, $12,
    $13, $14,
    $15, $16,
    $17
)
RETURNING id, tenant_id, wallet_id, group_id, name, public_address, encrypted_priv_key, key_version, policy_id, rotation_mode, rotation_interval_s, next_rotation_at, expires_at, status, revoked_reason, revoked_at, rail_native, on_chain_tx_hash, metadata, created_at, updated_at
`

type CreateSessionKeyParams struct {
	ID                string             `json:"id"`
	TenantID          string             `json:"tenant_id"`
	WalletID          string             `json:"wallet_id"`
	GroupID           string             `json:"group_id"`
	Name              string             `json:"name"`
	PublicAddress     string             `json:"public_address"`
	EncryptedPrivKey  []byte             `json:"encrypted_priv_key"`
	KeyVersion        int16              `json:"key_version"`
	PolicyID          pgtype.Text        `json:"policy_id"`
	RotationMode      string             `json:"rotation_mode"`
	RotationIntervalS int32              `json:"rotation_interval_s"`
	NextRotationAt    pgtype.Timestamptz `json:"next_rotation_at"`
	ExpiresAt         pgtype.Timestamptz `json:"expires_at"`
	Status            string             `json:"status"`
	RailNative        bool               `json:"rail_native"`
	OnChainTxHash     pgtype.Text        `json:"on_chain_tx_hash"`
	Metadata          []byte             `json:"metadata"`
}

// Session keys: delegated signers attached to a wallet, each carrying its
// own limit_policy and rotation schedule. The DB invariants are enforced
// by the schema (see migration 000004); these queries are kept minimal so
// the orchestration service can compose them in transactions.
func (q *Queries) CreateSessionKey(ctx context.Context, arg CreateSessionKeyParams) (SessionKey, error) {
	row := q.db.QueryRow(ctx, createSessionKey,
		arg.ID,
		arg.TenantID,
		arg.WalletID,
		arg.GroupID,
		arg.Name,
		arg.PublicAddress,
		arg.EncryptedPrivKey,
		arg.KeyVersion,
		arg.PolicyID,
		arg.RotationMode,
		arg.RotationIntervalS,
		arg.NextRotationAt,
		arg.ExpiresAt,
		arg.Status,
		arg.RailNative,
		arg.OnChainTxHash,
		arg.Metadata,
	)
	var i SessionKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WalletID,
		&i.GroupID,
		&i.Name,
		&i.PublicAddress,
		&i.EncryptedPrivKey,
		&i.KeyVersion,
		&i.PolicyID,
		&i.RotationMode,
		&i.RotationIntervalS,
		&i.NextRotationAt,
		&i.ExpiresAt,
		&i.Status,
		&i.RevokedReason,
		&i.RevokedAt,
		&i.RailNative,
		&i.OnChainTxHash,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveSessionKeyByPublicAddress = `-- name: GetActiveSessionKeyByPublicAddress :one
SELECT id, tenant_id, wallet_id, group_id, name, public_address, encrypted_priv_key, key_version, policy_id, rotation_mode, rotation_interval_s, next_rotation_at, expires_at, status, revoked_reason, revoked_at, rail_native, on_chain_tx_hash, metadata, created_at, updated_at FROM session_keys
WHERE public_address = $1 AND status = 'active'
`

// Hot path: when a transaction is signed with a session key, we identify
// the signer by its 0x-address and need the row's encrypted_priv_key +
// policy_id + status in one lookup. The partial index on (public_address)
// WHERE status='active' makes this O(1).
func (q *Queries) GetActiveSessionKeyByPublicAddress(ctx context.Context, publicAddress string) (SessionKey, error) {
	row := q.db.QueryRow(ctx, getActiveSessionKeyByPublicAddress, publicAddress)
	var i SessionKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WalletID,
		&i.GroupID,
		&i.Name,
		&i.PublicAddress,
		&i.EncryptedPrivKey,
		&i.KeyVersion,
		&i.PolicyID,
		&i.RotationMode,
		&i.RotationIntervalS,
		&i.NextRotationAt,
		&i.ExpiresAt,
		&i.Status,
		&i.RevokedReason,
		&i.RevokedAt,
		&i.RailNative,
		&i.OnChainTxHash,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionKeyByID = `-- name: GetSessionKeyByID :one
SELECT id, tenant_id, wallet_id, group_id, name, public_address, encrypted_priv_key, key_version, policy_id, rotation_mode, rotation_interval_s, next_rotation_at, expires_at, status, revoked_reason, revoked_at, rail_native, on_chain_tx_hash, metadata, created_at, updated_at FROM session_keys
WHERE id = $1
`

func (q *Queries) GetSessionKeyByID(ctx context.Context, id string) (SessionKey, error) {
	row := q.db.QueryRow(ctx, getSessionKeyByID, id)
	var i SessionKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WalletID,
		&i.GroupID,
		&i.Name,
		&i.PublicAddress,
		&i.EncryptedPrivKey,
		&i.KeyVersion,
		&i.PolicyID,
		&i.RotationMode,
		&i.RotationIntervalS,
		&i.NextRotationAt,
		&i.ExpiresAt,
		&i.Status,
		&i.RevokedReason,
		&i.RevokedAt,
		&i.RailNative,
		&i.OnChainTxHash,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listExpiredSessionKeys = `-- name: ListExpiredSessionKeys :many
SELECT id, tenant_id, wallet_id, group_id, name, public_address, encrypted_priv_key, key_version, policy_id, rotation_mode, rotation_interval_s, next_rotation_at, expires_at, status, revoked_reason, revoked_at, rail_native, on_chain_tx_hash, metadata, created_at, updated_at FROM session_keys
WHERE status IN ('active', 'rotating')
  AND expires_at <= $1
ORDER BY expires_at ASC
LIMIT $2
`

type ListExpiredSessionKeysParams struct {
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Limit     int32              `json:"limit"`
}

// Sweep: keys whose expires_at has passed but status still says
// active/rotating. The cron flips them to 'expired'.
func (q *Queries) ListExpiredSessionKeys(ctx context.Context, arg ListExpiredSessionKeysParams) ([]SessionKey, error) {
	rows, err := q.db.Query(ctx, listExpiredSessionKeys, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionKey{}
	for rows.Next() {
		var i SessionKey
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WalletID,
			&i.GroupID,
			&i.Name,
			&i.PublicAddress,
			&i.EncryptedPrivKey,
			&i.KeyVersion,
			&i.PolicyID,
			&i.RotationMode,
			&i.RotationIntervalS,
			&i.NextRotationAt,
			&i.ExpiresAt,
			&i.Status,
			&i.RevokedReason,
			&i.RevokedAt,
			&i.RailNative,
			&i.OnChainTxHash,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionKeysDueForRotation = `-- name: ListSessionKeysDueForRotation :many
SELECT id, tenant_id, wallet_id, group_id, name, public_address, encrypted_priv_key, key_version, policy_id, rotation_mode, rotation_interval_s, next_rotation_at, expires_at, status, revoked_reason, revoked_at, rail_native, on_chain_tx_hash, metadata, created_at, updated_at FROM session_keys
WHERE rotation_mode = 'auto_rotate'
  AND status = 'active'
  AND next_rotation_at <= $1
ORDER BY next_rotation_at ASC
LIMIT $2
`

type ListSessionKeysDueForRotationParams struct {
	NextRotationAt pgtype.Timestamptz `json:"next_rotation_at"`
	Limit          int32              `json:"limit"`
}

// Background worker scans this every cycle. The partial index on
// next_rotation_at filtered to (rotation_mode='auto_rotate' AND
// status='active') keeps the scan tight regardless of total population.
func (q *Queries) ListSessionKeysDueForRotation(ctx context.Context, arg ListSessionKeysDueForRotationParams) ([]SessionKey, error) {
	rows, err := q.db.Query(ctx, listSessionKeysDueForRotation, arg.NextRotationAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionKey{}
	for rows.Next() {
		var i SessionKey
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WalletID,
			&i.GroupID,
			&i.Name,
			&i.PublicAddress,
			&i.EncryptedPrivKey,
			&i.KeyVersion,
			&i.PolicyID,
			&i.RotationMode,
			&i.RotationIntervalS,
			&i.NextRotationAt,
			&i.ExpiresAt,
			&i.Status,
			&i.RevokedReason,
			&i.RevokedAt,
			&i.RailNative,
			&i.OnChainTxHash,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionKeysForTenant = `-- name: ListSessionKeysForTenant :many
SELECT id, tenant_id, wallet_id, group_id, name, public_address, encrypted_priv_key, key_version, policy_id, rotation_mode, rotation_interval_s, next_rotation_at, expires_at, status, revoked_reason, revoked_at, rail_native, on_chain_tx_hash, metadata, created_at, updated_at FROM session_keys
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSessionKeysForTenantParams struct {
	TenantID string `json:"tenant_id"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListSessionKeysForTenant(ctx context.Context, arg ListSessionKeysForTenantParams) ([]SessionKey, error) {
	rows, err := q.db.Query(ctx, listSessionKeysForTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionKey{}
	for rows.Next() {
		var i SessionKey
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WalletID,
			&i.GroupID,
			&i.Name,
			&i.PublicAddress,
			&i.EncryptedPrivKey,
			&i.KeyVersion,
			&i.PolicyID,
			&i.RotationMode,
			&i.RotationIntervalS,
			&i.NextRotationAt,
			&i.ExpiresAt,
			&i.Status,
			&i.RevokedReason,
			&i.RevokedAt,
			&i.RailNative,
			&i.OnChainTxHash,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionKeysForWallet = `-- name: ListSessionKeysForWallet :many
SELECT id, tenant_id, wallet_id, group_id, name, public_address, encrypted_priv_key, key_version, policy_id, rotation_mode, rotation_interval_s, next_rotation_at, expires_at, status, revoked_reason, revoked_at, rail_native, on_chain_tx_hash, metadata, created_at, updated_at FROM session_keys
WHERE wallet_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSessionKeysForWalletParams struct {
	WalletID string `json:"wallet_id"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

// Dashboard listing. Includes revoked / expired so customers can audit
// history; the UI strikes through inactive rows.
func (q *Queries) ListSessionKeysForWallet(ctx context.Context, arg ListSessionKeysForWalletParams) ([]SessionKey, error) {
	rows, err := q.db.Query(ctx, listSessionKeysForWallet, arg.WalletID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionKey{}
	for rows.Next() {
		var i SessionKey
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WalletID,
			&i.GroupID,
			&i.Name,
			&i.PublicAddress,
			&i.EncryptedPrivKey,
			&i.KeyVersion,
			&i.PolicyID,
			&i.RotationMode,
			&i.RotationIntervalS,
			&i.NextRotationAt,
			&i.ExpiresAt,
			&i.Status,
			&i.RevokedReason,
			&i.RevokedAt,
			&i.RailNative,
			&i.OnChainTxHash,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSessionKey = `-- name: RevokeSessionKey :one
UPDATE session_keys
SET status         = 'revoked',
    revoked_reason = $2,
    revoked_at     = NOW()
WHERE id = $1 AND status = 'active'
RETURNING id, tenant_id, wallet_id, group_id, name, public_address, encrypted_priv_key, key_version, policy_id, rotation_mode, rotation_interval_s, next_rotation_at, expires_at, status, revoked_reason, revoked_at, rail_native, on_chain_tx_hash, metadata, created_at, updated_at
`

type RevokeSessionKeyParams struct {
	ID            string      `json:"id"`
	RevokedReason pgtype.Text `json:"revoked_reason"`
}

// Idempotent at the SQL layer via the WHERE status='active' guard —
// repeat revokes don't overwrite the original revoked_at.
func (q *Queries) RevokeSessionKey(ctx context.Context, arg RevokeSessionKeyParams) (SessionKey, error) {
	row := q.db.QueryRow(ctx, revokeSessionKey, arg.ID, arg.RevokedReason)
	var i SessionKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WalletID,
		&i.GroupID,
		&i.Name,
		&i.PublicAddress,
		&i.EncryptedPrivKey,
		&i.KeyVersion,
		&i.PolicyID,
		&i.RotationMode,
		&i.RotationIntervalS,
		&i.NextRotationAt,
		&i.ExpiresAt,
		&i.Status,
		&i.RevokedReason,
		&i.RevokedAt,
		&i.RailNative,
		&i.OnChainTxHash,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSessionKeyNextRotation = `-- name: UpdateSessionKeyNextRotation :exec
UPDATE session_keys
SET next_rotation_at = $2
WHERE id = $1
`

type UpdateSessionKeyNextRotationParams struct {
	ID             string             `json:"id"`
	NextRotationAt pgtype.Timestamptz `json:"next_rotation_at"`
}

// Atomically reset the auto-rotation cursor after the worker hands out a
// replacement key.
func (q *Queries) UpdateSessionKeyNextRotation(ctx context.Context, arg UpdateSessionKeyNextRotationParams) error {
	_, err := q.db.Exec(ctx, updateSessionKeyNextRotation, arg.ID, arg.NextRotationAt)
	return err
}

const updateSessionKeyStatus = `-- name: UpdateSessionKeyStatus :one
UPDATE session_keys
SET status = $2
WHERE id = $1
RETURNING id, tenant_id, wallet_id, group_id, name, public_address, encrypted_priv_key, key_version, policy_id, rotation_mode, rotation_interval_s, next_rotation_at, expires_at, status, revoked_reason, revoked_at, rail_native, on_chain_tx_hash, metadata, created_at, updated_at
`

type UpdateSessionKeyStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateSessionKeyStatus(ctx context.Context, arg UpdateSessionKeyStatusParams) (SessionKey, error) {
	row := q.db.QueryRow(ctx, updateSessionKeyStatus, arg.ID, arg.Status)
	var i SessionKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WalletID,
		&i.GroupID,
		&i.Name,
		&i.PublicAddress,
		&i.EncryptedPrivKey,
		&i.KeyVersion,
		&i.PolicyID,
		&i.RotationMode,
		&i.RotationIntervalS,
		&i.NextRotationAt,
		&i.ExpiresAt,
		&i.Status,
		&i.RevokedReason,
		&i.RevokedAt,
		&i.RailNative,
		&i.OnChainTxHash,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
