// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package sqlcgen

import (
	"context"
)

const createTenant = `-- name: CreateTenant :one

INSERT INTO tenants (
    id, name, primary_email, plan, status, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, name, primary_email, plan, status, metadata, created_at, updated_at
`

type CreateTenantParams struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	PrimaryEmail string `json:"primary_email"`
	Plan         string `json:"plan"`
	Status       string `json:"status"`
	Metadata     []byte `json:"metadata"`
}

// Tenants are ATARA-Pay's primary isolation unit.
// Queries here are used by signup, billing, and the customer self-service
// account page.
func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.ID,
		arg.Name,
		arg.PrimaryEmail,
		arg.Plan,
		arg.Status,
		arg.Metadata,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PrimaryEmail,
		&i.Plan,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByEmail = `-- name: GetTenantByEmail :one
SELECT id, name, primary_email, plan, status, metadata, created_at, updated_at FROM tenants
WHERE primary_email = $1
`

func (q *Queries) GetTenantByEmail(ctx context.Context, primaryEmail string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByEmail, primaryEmail)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PrimaryEmail,
		&i.Plan,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, primary_email, plan, status, metadata, created_at, updated_at FROM tenants
WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PrimaryEmail,
		&i.Plan,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveTenants = `-- name: ListActiveTenants :many
SELECT id, name, primary_email, plan, status, metadata, created_at, updated_at FROM tenants
WHERE status = 'active'
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListActiveTenantsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// Used by background sweepers and the admin console.
func (q *Queries) ListActiveTenants(ctx context.Context, arg ListActiveTenantsParams) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listActiveTenants, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PrimaryEmail,
			&i.Plan,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenantPlan = `-- name: UpdateTenantPlan :one
UPDATE tenants
SET plan = $2
WHERE id = $1
RETURNING id, name, primary_email, plan, status, metadata, created_at, updated_at
`

type UpdateTenantPlanParams struct {
	ID   string `json:"id"`
	Plan string `json:"plan"`
}

func (q *Queries) UpdateTenantPlan(ctx context.Context, arg UpdateTenantPlanParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantPlan, arg.ID, arg.Plan)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PrimaryEmail,
		&i.Plan,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTenantStatus = `-- name: UpdateTenantStatus :one
UPDATE tenants
SET status = $2
WHERE id = $1
RETURNING id, name, primary_email, plan, status, metadata, created_at, updated_at
`

type UpdateTenantStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateTenantStatus(ctx context.Context, arg UpdateTenantStatusParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantStatus, arg.ID, arg.Status)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PrimaryEmail,
		&i.Plan,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
