// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTransaction = `-- name: CreateTransaction :one

INSERT INTO transactions (
    id, tenant_id, wallet_id, group_id, rail, chain,
    direction, counterparty,
    amount, asset, amount_usd,
    status, tx_hash, provider_tx_id,
    session_key_id, initiated_by_user, initiated_by_apikey,
    idempotency_key, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8,
    $9, $10, $11,
    $12, $13, $14,
    $15, $16, $17,
    $18, $19
)
RETURNING id, tenant_id, wallet_id, group_id, rail, chain, direction, counterparty, amount, asset, amount_usd, status, tx_hash, block_number, provider_tx_id, session_key_id, initiated_by_user, initiated_by_apikey, idempotency_key, error_code, error_message, metadata, created_at, updated_at, broadcast_at, confirmed_at
`

type CreateTransactionParams struct {
	ID                string         `json:"id"`
	TenantID          string         `json:"tenant_id"`
	WalletID          string         `json:"wallet_id"`
	GroupID           string         `json:"group_id"`
	Rail              string         `json:"rail"`
	Chain             string         `json:"chain"`
	Direction         string         `json:"direction"`
	Counterparty      string         `json:"counterparty"`
	Amount            string         `json:"amount"`
	Asset             string         `json:"asset"`
	AmountUsd         pgtype.Numeric `json:"amount_usd"`
	Status            string         `json:"status"`
	TxHash            pgtype.Text    `json:"tx_hash"`
	ProviderTxID      pgtype.Text    `json:"provider_tx_id"`
	SessionKeyID      pgtype.Text    `json:"session_key_id"`
	InitiatedByUser   pgtype.Text    `json:"initiated_by_user"`
	InitiatedByApikey pgtype.Text    `json:"initiated_by_apikey"`
	IdempotencyKey    pgtype.Text    `json:"idempotency_key"`
	Metadata          []byte         `json:"metadata"`
}

// Money-movement audit table. Append-mostly: status fields advance via
// UPDATE but rows are never deleted.
func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.ID,
		arg.TenantID,
		arg.WalletID,
		arg.GroupID,
		arg.Rail,
		arg.Chain,
		arg.Direction,
		arg.Counterparty,
		arg.Amount,
		arg.Asset,
		arg.AmountUsd,
		arg.Status,
		arg.TxHash,
		arg.ProviderTxID,
		arg.SessionKeyID,
		arg.InitiatedByUser,
		arg.InitiatedByApikey,
		arg.IdempotencyKey,
		arg.Metadata,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WalletID,
		&i.GroupID,
		&i.Rail,
		&i.Chain,
		&i.Direction,
		&i.Counterparty,
		&i.Amount,
		&i.Asset,
		&i.AmountUsd,
		&i.Status,
		&i.TxHash,
		&i.BlockNumber,
		&i.ProviderTxID,
		&i.SessionKeyID,
		&i.InitiatedByUser,
		&i.InitiatedByApikey,
		&i.IdempotencyKey,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BroadcastAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const getTransactionByID = `-- name: GetTransactionByID :one
SELECT id, tenant_id, wallet_id, group_id, rail, chain, direction, counterparty, amount, asset, amount_usd, status, tx_hash, block_number, provider_tx_id, session_key_id, initiated_by_user, initiated_by_apikey, idempotency_key, error_code, error_message, metadata, created_at, updated_at, broadcast_at, confirmed_at FROM transactions
WHERE id = $1
`

func (q *Queries) GetTransactionByID(ctx context.Context, id string) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByID, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WalletID,
		&i.GroupID,
		&i.Rail,
		&i.Chain,
		&i.Direction,
		&i.Counterparty,
		&i.Amount,
		&i.Asset,
		&i.AmountUsd,
		&i.Status,
		&i.TxHash,
		&i.BlockNumber,
		&i.ProviderTxID,
		&i.SessionKeyID,
		&i.InitiatedByUser,
		&i.InitiatedByApikey,
		&i.IdempotencyKey,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BroadcastAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const getTransactionByIdempotencyKey = `-- name: GetTransactionByIdempotencyKey :one
SELECT id, tenant_id, wallet_id, group_id, rail, chain, direction, counterparty, amount, asset, amount_usd, status, tx_hash, block_number, provider_tx_id, session_key_id, initiated_by_user, initiated_by_apikey, idempotency_key, error_code, error_message, metadata, created_at, updated_at, broadcast_at, confirmed_at FROM transactions
WHERE tenant_id = $1 AND idempotency_key = $2
`

type GetTransactionByIdempotencyKeyParams struct {
	TenantID       string      `json:"tenant_id"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
}

func (q *Queries) GetTransactionByIdempotencyKey(ctx context.Context, arg GetTransactionByIdempotencyKeyParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByIdempotencyKey, arg.TenantID, arg.IdempotencyKey)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WalletID,
		&i.GroupID,
		&i.Rail,
		&i.Chain,
		&i.Direction,
		&i.Counterparty,
		&i.Amount,
		&i.Asset,
		&i.AmountUsd,
		&i.Status,
		&i.TxHash,
		&i.BlockNumber,
		&i.ProviderTxID,
		&i.SessionKeyID,
		&i.InitiatedByUser,
		&i.InitiatedByApikey,
		&i.IdempotencyKey,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BroadcastAt,
		&i.ConfirmedAt,
	)
	return i, err
}

const listTransactionsByGroup = `-- name: ListTransactionsByGroup :many
SELECT id, tenant_id, wallet_id, group_id, rail, chain, direction, counterparty, amount, asset, amount_usd, status, tx_hash, block_number, provider_tx_id, session_key_id, initiated_by_user, initiated_by_apikey, idempotency_key, error_code, error_message, metadata, created_at, updated_at, broadcast_at, confirmed_at FROM transactions
WHERE group_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByGroupParams struct {
	GroupID string `json:"group_id"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListTransactionsByGroup(ctx context.Context, arg ListTransactionsByGroupParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByGroup, arg.GroupID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WalletID,
			&i.GroupID,
			&i.Rail,
			&i.Chain,
			&i.Direction,
			&i.Counterparty,
			&i.Amount,
			&i.Asset,
			&i.AmountUsd,
			&i.Status,
			&i.TxHash,
			&i.BlockNumber,
			&i.ProviderTxID,
			&i.SessionKeyID,
			&i.InitiatedByUser,
			&i.InitiatedByApikey,
			&i.IdempotencyKey,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BroadcastAt,
			&i.ConfirmedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByTenant = `-- name: ListTransactionsByTenant :many
SELECT id, tenant_id, wallet_id, group_id, rail, chain, direction, counterparty, amount, asset, amount_usd, status, tx_hash, block_number, provider_tx_id, session_key_id, initiated_by_user, initiated_by_apikey, idempotency_key, error_code, error_message, metadata, created_at, updated_at, broadcast_at, confirmed_at FROM transactions
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByTenantParams struct {
	TenantID string `json:"tenant_id"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListTransactionsByTenant(ctx context.Context, arg ListTransactionsByTenantParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WalletID,
			&i.GroupID,
			&i.Rail,
			&i.Chain,
			&i.Direction,
			&i.Counterparty,
			&i.Amount,
			&i.Asset,
			&i.AmountUsd,
			&i.Status,
			&i.TxHash,
			&i.BlockNumber,
			&i.ProviderTxID,
			&i.SessionKeyID,
			&i.InitiatedByUser,
			&i.InitiatedByApikey,
			&i.IdempotencyKey,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BroadcastAt,
			&i.ConfirmedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByWallet = `-- name: ListTransactionsByWallet :many
SELECT id, tenant_id, wallet_id, group_id, rail, chain, direction, counterparty, amount, asset, amount_usd, status, tx_hash, block_number, provider_tx_id, session_key_id, initiated_by_user, initiated_by_apikey, idempotency_key, error_code, error_message, metadata, created_at, updated_at, broadcast_at, confirmed_at FROM transactions
WHERE wallet_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListTransactionsByWalletParams struct {
	WalletID string `json:"wallet_id"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListTransactionsByWallet(ctx context.Context, arg ListTransactionsByWalletParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByWallet, arg.WalletID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WalletID,
			&i.GroupID,
			&i.Rail,
			&i.Chain,
			&i.Direction,
			&i.Counterparty,
			&i.Amount,
			&i.Asset,
			&i.AmountUsd,
			&i.Status,
			&i.TxHash,
			&i.BlockNumber,
			&i.ProviderTxID,
			&i.SessionKeyID,
			&i.InitiatedByUser,
			&i.InitiatedByApikey,
			&i.IdempotencyKey,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BroadcastAt,
			&i.ConfirmedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransactionStatus = `-- name: UpdateTransactionStatus :one
UPDATE transactions
SET status      = $2,
    tx_hash     = COALESCE($3, tx_hash),
    block_number = COALESCE($4, block_number),
    confirmed_at = CASE WHEN $2 IN ('succeeded', 'failed') THEN NOW() ELSE confirmed_at END
WHERE id = $1
RETURNING id, tenant_id, wallet_id, group_id, rail, chain, direction, counterparty, amount, asset, amount_usd, status, tx_hash, block_number, provider_tx_id, session_key_id, initiated_by_user, initiated_by_apikey, idempotency_key, error_code, error_message, metadata, created_at, updated_at, broadcast_at, confirmed_at
`

type UpdateTransactionStatusParams struct {
	ID          string      `json:"id"`
	Status      string      `json:"status"`
	TxHash      pgtype.Text `json:"tx_hash"`
	BlockNumber pgtype.Int8 `json:"block_number"`
}

func (q *Queries) UpdateTransactionStatus(ctx context.Context, arg UpdateTransactionStatusParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, updateTransactionStatus,
		arg.ID,
		arg.Status,
		arg.TxHash,
		arg.BlockNumber,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WalletID,
		&i.GroupID,
		&i.Rail,
		&i.Chain,
		&i.Direction,
		&i.Counterparty,
		&i.Amount,
		&i.Asset,
		&i.AmountUsd,
		&i.Status,
		&i.TxHash,
		&i.BlockNumber,
		&i.ProviderTxID,
		&i.SessionKeyID,
		&i.InitiatedByUser,
		&i.InitiatedByApikey,
		&i.IdempotencyKey,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BroadcastAt,
		&i.ConfirmedAt,
	)
	return i, err
}
