// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage_counters.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUsageCounter = `-- name: GetUsageCounter :one
SELECT policy_id, period_key, used_amount, used_asset, last_tx_id, flushed_at FROM usage_counters
WHERE policy_id = $1 AND period_key = $2
`

type GetUsageCounterParams struct {
	PolicyID  string `json:"policy_id"`
	PeriodKey string `json:"period_key"`
}

func (q *Queries) GetUsageCounter(ctx context.Context, arg GetUsageCounterParams) (UsageCounter, error) {
	row := q.db.QueryRow(ctx, getUsageCounter, arg.PolicyID, arg.PeriodKey)
	var i UsageCounter
	err := row.Scan(
		&i.PolicyID,
		&i.PeriodKey,
		&i.UsedAmount,
		&i.UsedAsset,
		&i.LastTxID,
		&i.FlushedAt,
	)
	return i, err
}

const listUsageCountersForPolicy = `-- name: ListUsageCountersForPolicy :many
SELECT policy_id, period_key, used_amount, used_asset, last_tx_id, flushed_at FROM usage_counters
WHERE policy_id = $1
ORDER BY period_key DESC
`

// Used by the dashboard "remaining today / this week / this month" view.
func (q *Queries) ListUsageCountersForPolicy(ctx context.Context, policyID string) ([]UsageCounter, error) {
	rows, err := q.db.Query(ctx, listUsageCountersForPolicy, policyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageCounter{}
	for rows.Next() {
		var i UsageCounter
		if err := rows.Scan(
			&i.PolicyID,
			&i.PeriodKey,
			&i.UsedAmount,
			&i.UsedAsset,
			&i.LastTxID,
			&i.FlushedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUsageCounter = `-- name: UpsertUsageCounter :one

INSERT INTO usage_counters (
    policy_id, period_key, used_amount, used_asset, last_tx_id
) VALUES (
    $1, $2, $3, $4, $5
)
ON CONFLICT (policy_id, period_key) DO UPDATE
SET used_amount = GREATEST(usage_counters.used_amount, EXCLUDED.used_amount),
    used_asset  = EXCLUDED.used_asset,
    last_tx_id  = EXCLUDED.last_tx_id,
    flushed_at  = NOW()
RETURNING policy_id, period_key, used_amount, used_asset, last_tx_id, flushed_at
`

type UpsertUsageCounterParams struct {
	PolicyID   string      `json:"policy_id"`
	PeriodKey  string      `json:"period_key"`
	UsedAmount string      `json:"used_amount"`
	UsedAsset  string      `json:"used_asset"`
	LastTxID   pgtype.Text `json:"last_tx_id"`
}

// Durable mirror of the hot-path Redis counters. Redis is the canonical
// source for live values; PG is the persisted copy flushed periodically
// so audits, reports, and Redis-outage recovery work.
//
// period_key formats:
//
//	daily:2026-05-20
//	weekly:2026-W21
//	monthly:2026-05
//
// Used both by the periodic Redis → PG flush and as a fallback path when
// Redis is unavailable. ON CONFLICT updates used_amount monotonically;
// we never go backwards (Redis is authoritative for live values).
func (q *Queries) UpsertUsageCounter(ctx context.Context, arg UpsertUsageCounterParams) (UsageCounter, error) {
	row := q.db.QueryRow(ctx, upsertUsageCounter,
		arg.PolicyID,
		arg.PeriodKey,
		arg.UsedAmount,
		arg.UsedAsset,
		arg.LastTxID,
	)
	var i UsageCounter
	err := row.Scan(
		&i.PolicyID,
		&i.PeriodKey,
		&i.UsedAmount,
		&i.UsedAsset,
		&i.LastTxID,
		&i.FlushedAt,
	)
	return i, err
}
