// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"
)

const createUser = `-- name: CreateUser :one

INSERT INTO users (
    id, tenant_id, email, password_hash, role
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, tenant_id, email, password_hash, role, email_verified, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	ID           string `json:"id"`
	TenantID     string `json:"tenant_id"`
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
	Role         string `json:"role"`
}

// Users are the humans logging into the dashboard. Always tenant-scoped.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.TenantID,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :many
SELECT id, tenant_id, email, password_hash, role, email_verified, last_login_at, created_at, updated_at FROM users
WHERE email = $1
ORDER BY created_at ASC
`

// Some sign-in flows look up across tenants (e.g. user belongs to multiple
// companies). Returns 0..n rows.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) ([]User, error) {
	rows, err := q.db.Query(ctx, getUserByEmail, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.EmailVerified,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmailInTenant = `-- name: GetUserByEmailInTenant :one
SELECT id, tenant_id, email, password_hash, role, email_verified, last_login_at, created_at, updated_at FROM users
WHERE tenant_id = $1 AND email = $2
`

type GetUserByEmailInTenantParams struct {
	TenantID string `json:"tenant_id"`
	Email    string `json:"email"`
}

// Login flow: email + tenant_id is the unique pair.
func (q *Queries) GetUserByEmailInTenant(ctx context.Context, arg GetUserByEmailInTenantParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailInTenant, arg.TenantID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, tenant_id, email, password_hash, role, email_verified, last_login_at, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.EmailVerified,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsersInTenant = `-- name: ListUsersInTenant :many
SELECT id, tenant_id, email, password_hash, role, email_verified, last_login_at, created_at, updated_at FROM users
WHERE tenant_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListUsersInTenant(ctx context.Context, tenantID string) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersInTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.EmailVerified,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE users
SET email_verified = TRUE
WHERE id = $1
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markEmailVerified, id)
	return err
}

const touchUserLogin = `-- name: TouchUserLogin :exec
UPDATE users
SET last_login_at = NOW()
WHERE id = $1
`

func (q *Queries) TouchUserLogin(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchUserLogin, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           string `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
