// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: virtual_addresses.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVirtualAddress = `-- name: CreateVirtualAddress :one

INSERT INTO virtual_addresses (
    id, tenant_id, wallet_id, group_id, label, address, registration_tx_hash, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, tenant_id, wallet_id, group_id, label, address, registration_tx_hash, metadata, created_at
`

type CreateVirtualAddressParams struct {
	ID                 string      `json:"id"`
	TenantID           string      `json:"tenant_id"`
	WalletID           string      `json:"wallet_id"`
	GroupID            string      `json:"group_id"`
	Label              string      `json:"label"`
	Address            string      `json:"address"`
	RegistrationTxHash pgtype.Text `json:"registration_tx_hash"`
	Metadata           []byte      `json:"metadata"`
}

// TIP-1022 virtual addresses. (wallet_id, label) is the natural idempotency
// key — the same label always resolves to the same on-chain address.
func (q *Queries) CreateVirtualAddress(ctx context.Context, arg CreateVirtualAddressParams) (VirtualAddress, error) {
	row := q.db.QueryRow(ctx, createVirtualAddress,
		arg.ID,
		arg.TenantID,
		arg.WalletID,
		arg.GroupID,
		arg.Label,
		arg.Address,
		arg.RegistrationTxHash,
		arg.Metadata,
	)
	var i VirtualAddress
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WalletID,
		&i.GroupID,
		&i.Label,
		&i.Address,
		&i.RegistrationTxHash,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getVirtualAddressByAddress = `-- name: GetVirtualAddressByAddress :one
SELECT id, tenant_id, wallet_id, group_id, label, address, registration_tx_hash, metadata, created_at FROM virtual_addresses
WHERE address = $1
`

// Reverse lookup for incoming-deposit webhooks: "which virtual address
// received this transfer?"
func (q *Queries) GetVirtualAddressByAddress(ctx context.Context, address string) (VirtualAddress, error) {
	row := q.db.QueryRow(ctx, getVirtualAddressByAddress, address)
	var i VirtualAddress
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WalletID,
		&i.GroupID,
		&i.Label,
		&i.Address,
		&i.RegistrationTxHash,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getVirtualAddressByLabel = `-- name: GetVirtualAddressByLabel :one
SELECT id, tenant_id, wallet_id, group_id, label, address, registration_tx_hash, metadata, created_at FROM virtual_addresses
WHERE wallet_id = $1 AND label = $2
`

type GetVirtualAddressByLabelParams struct {
	WalletID string `json:"wallet_id"`
	Label    string `json:"label"`
}

// Idempotency path: if the customer asks for label "invoice-42" twice we
// return the same row (and skip re-registering on chain).
func (q *Queries) GetVirtualAddressByLabel(ctx context.Context, arg GetVirtualAddressByLabelParams) (VirtualAddress, error) {
	row := q.db.QueryRow(ctx, getVirtualAddressByLabel, arg.WalletID, arg.Label)
	var i VirtualAddress
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WalletID,
		&i.GroupID,
		&i.Label,
		&i.Address,
		&i.RegistrationTxHash,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listVirtualAddressesForWallet = `-- name: ListVirtualAddressesForWallet :many
SELECT id, tenant_id, wallet_id, group_id, label, address, registration_tx_hash, metadata, created_at FROM virtual_addresses
WHERE wallet_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListVirtualAddressesForWalletParams struct {
	WalletID string `json:"wallet_id"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListVirtualAddressesForWallet(ctx context.Context, arg ListVirtualAddressesForWalletParams) ([]VirtualAddress, error) {
	rows, err := q.db.Query(ctx, listVirtualAddressesForWallet, arg.WalletID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VirtualAddress{}
	for rows.Next() {
		var i VirtualAddress
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WalletID,
			&i.GroupID,
			&i.Label,
			&i.Address,
			&i.RegistrationTxHash,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
