// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallet_groups.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWalletGroup = `-- name: CreateWalletGroup :one

INSERT INTO wallet_groups (
    id, tenant_id, owner_type, owner_ref, parent_group_id,
    custody, display_name, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, tenant_id, owner_type, owner_ref, parent_group_id, custody, display_name, metadata, created_at, updated_at, deleted_at
`

type CreateWalletGroupParams struct {
	ID            string      `json:"id"`
	TenantID      string      `json:"tenant_id"`
	OwnerType     string      `json:"owner_type"`
	OwnerRef      string      `json:"owner_ref"`
	ParentGroupID pgtype.Text `json:"parent_group_id"`
	Custody       string      `json:"custody"`
	DisplayName   pgtype.Text `json:"display_name"`
	Metadata      []byte      `json:"metadata"`
}

// Wallet groups bundle a logical "owner" (user / agent / merchant / treasury)
// and the per-rail wallets that belong to it. One group typically holds
// 2-3 wallets: one CrossMint, one Tempo, eventually one Loka-LN.
func (q *Queries) CreateWalletGroup(ctx context.Context, arg CreateWalletGroupParams) (WalletGroup, error) {
	row := q.db.QueryRow(ctx, createWalletGroup,
		arg.ID,
		arg.TenantID,
		arg.OwnerType,
		arg.OwnerRef,
		arg.ParentGroupID,
		arg.Custody,
		arg.DisplayName,
		arg.Metadata,
	)
	var i WalletGroup
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OwnerType,
		&i.OwnerRef,
		&i.ParentGroupID,
		&i.Custody,
		&i.DisplayName,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWalletGroupByID = `-- name: GetWalletGroupByID :one
SELECT id, tenant_id, owner_type, owner_ref, parent_group_id, custody, display_name, metadata, created_at, updated_at, deleted_at FROM wallet_groups
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetWalletGroupByID(ctx context.Context, id string) (WalletGroup, error) {
	row := q.db.QueryRow(ctx, getWalletGroupByID, id)
	var i WalletGroup
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OwnerType,
		&i.OwnerRef,
		&i.ParentGroupID,
		&i.Custody,
		&i.DisplayName,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWalletGroupByOwnerRef = `-- name: GetWalletGroupByOwnerRef :one
SELECT id, tenant_id, owner_type, owner_ref, parent_group_id, custody, display_name, metadata, created_at, updated_at, deleted_at FROM wallet_groups
WHERE tenant_id = $1 AND owner_ref = $2 AND deleted_at IS NULL
`

type GetWalletGroupByOwnerRefParams struct {
	TenantID string `json:"tenant_id"`
	OwnerRef string `json:"owner_ref"`
}

// The lookup the dual-create endpoint needs to honor idempotency: if the
// customer POSTs /v1/wallet-groups twice with the same owner_ref, we
// return the existing group instead of failing.
func (q *Queries) GetWalletGroupByOwnerRef(ctx context.Context, arg GetWalletGroupByOwnerRefParams) (WalletGroup, error) {
	row := q.db.QueryRow(ctx, getWalletGroupByOwnerRef, arg.TenantID, arg.OwnerRef)
	var i WalletGroup
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OwnerType,
		&i.OwnerRef,
		&i.ParentGroupID,
		&i.Custody,
		&i.DisplayName,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAgentGroupsForParent = `-- name: ListAgentGroupsForParent :many
SELECT id, tenant_id, owner_type, owner_ref, parent_group_id, custody, display_name, metadata, created_at, updated_at, deleted_at FROM wallet_groups
WHERE parent_group_id = $1 AND deleted_at IS NULL
ORDER BY created_at ASC
`

// All agent groups belonging to a particular user group (parent → child).
// Used by the dashboard to show "Alice's agents" under Alice's user group.
func (q *Queries) ListAgentGroupsForParent(ctx context.Context, parentGroupID pgtype.Text) ([]WalletGroup, error) {
	rows, err := q.db.Query(ctx, listAgentGroupsForParent, parentGroupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WalletGroup{}
	for rows.Next() {
		var i WalletGroup
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OwnerType,
			&i.OwnerRef,
			&i.ParentGroupID,
			&i.Custody,
			&i.DisplayName,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWalletGroupsInTenant = `-- name: ListWalletGroupsInTenant :many
SELECT id, tenant_id, owner_type, owner_ref, parent_group_id, custody, display_name, metadata, created_at, updated_at, deleted_at FROM wallet_groups
WHERE tenant_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWalletGroupsInTenantParams struct {
	TenantID string `json:"tenant_id"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

// Dashboard listing. Filter by owner_type (e.g. only show agents) is
// handled at the application layer.
func (q *Queries) ListWalletGroupsInTenant(ctx context.Context, arg ListWalletGroupsInTenantParams) ([]WalletGroup, error) {
	rows, err := q.db.Query(ctx, listWalletGroupsInTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WalletGroup{}
	for rows.Next() {
		var i WalletGroup
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.OwnerType,
			&i.OwnerRef,
			&i.ParentGroupID,
			&i.Custody,
			&i.DisplayName,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteWalletGroup = `-- name: SoftDeleteWalletGroup :exec
UPDATE wallet_groups
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

// Soft delete. The row stays so audit / reporting can still find it.
// Cascades to the wallets table via the foreign key (which then go
// status='deleted' through the same touch trigger).
func (q *Queries) SoftDeleteWalletGroup(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, softDeleteWalletGroup, id)
	return err
}

const updateWalletGroupDisplayName = `-- name: UpdateWalletGroupDisplayName :one
UPDATE wallet_groups
SET display_name = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, tenant_id, owner_type, owner_ref, parent_group_id, custody, display_name, metadata, created_at, updated_at, deleted_at
`

type UpdateWalletGroupDisplayNameParams struct {
	ID          string      `json:"id"`
	DisplayName pgtype.Text `json:"display_name"`
}

func (q *Queries) UpdateWalletGroupDisplayName(ctx context.Context, arg UpdateWalletGroupDisplayNameParams) (WalletGroup, error) {
	row := q.db.QueryRow(ctx, updateWalletGroupDisplayName, arg.ID, arg.DisplayName)
	var i WalletGroup
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.OwnerType,
		&i.OwnerRef,
		&i.ParentGroupID,
		&i.Custody,
		&i.DisplayName,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
