// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: wallets.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWallet = `-- name: CreateWallet :one

INSERT INTO wallets (
    id, group_id, tenant_id, rail, chain, address, provider_locator,
    custody, encrypted_private_key, key_version, status, metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, group_id, tenant_id, rail, chain, address, provider_locator, custody, encrypted_private_key, key_version, status, metadata, created_at, updated_at
`

type CreateWalletParams struct {
	ID                  string      `json:"id"`
	GroupID             string      `json:"group_id"`
	TenantID            string      `json:"tenant_id"`
	Rail                string      `json:"rail"`
	Chain               string      `json:"chain"`
	Address             string      `json:"address"`
	ProviderLocator     string      `json:"provider_locator"`
	Custody             string      `json:"custody"`
	EncryptedPrivateKey []byte      `json:"encrypted_private_key"`
	KeyVersion          pgtype.Int2 `json:"key_version"`
	Status              string      `json:"status"`
	Metadata            []byte      `json:"metadata"`
}

// One wallet = one on-chain account on one rail (CrossMint / Tempo /
// Loka-LN). Wallets belong to exactly one wallet_group via group_id.
func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet,
		arg.ID,
		arg.GroupID,
		arg.TenantID,
		arg.Rail,
		arg.Chain,
		arg.Address,
		arg.ProviderLocator,
		arg.Custody,
		arg.EncryptedPrivateKey,
		arg.KeyVersion,
		arg.Status,
		arg.Metadata,
	)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.TenantID,
		&i.Rail,
		&i.Chain,
		&i.Address,
		&i.ProviderLocator,
		&i.Custody,
		&i.EncryptedPrivateKey,
		&i.KeyVersion,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletByAddress = `-- name: GetWalletByAddress :one
SELECT id, group_id, tenant_id, rail, chain, address, provider_locator, custody, encrypted_private_key, key_version, status, metadata, created_at, updated_at FROM wallets
WHERE address = $1 AND status = 'active'
`

// Reverse lookup for incoming-transfer webhooks. The address index is
// partial on status='active' so deleted wallets don't clutter it.
func (q *Queries) GetWalletByAddress(ctx context.Context, address string) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletByAddress, address)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.TenantID,
		&i.Rail,
		&i.Chain,
		&i.Address,
		&i.ProviderLocator,
		&i.Custody,
		&i.EncryptedPrivateKey,
		&i.KeyVersion,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletByGroupAndRail = `-- name: GetWalletByGroupAndRail :one
SELECT id, group_id, tenant_id, rail, chain, address, provider_locator, custody, encrypted_private_key, key_version, status, metadata, created_at, updated_at FROM wallets
WHERE group_id = $1 AND rail = $2 AND status = 'active'
`

type GetWalletByGroupAndRailParams struct {
	GroupID string `json:"group_id"`
	Rail    string `json:"rail"`
}

// Hot path: when /v1/transactions or /v1/onramp resolves a group to a
// specific rail's wallet, this query is what runs. The
// (group_id, rail, chain) UNIQUE index makes it O(1).
func (q *Queries) GetWalletByGroupAndRail(ctx context.Context, arg GetWalletByGroupAndRailParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletByGroupAndRail, arg.GroupID, arg.Rail)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.TenantID,
		&i.Rail,
		&i.Chain,
		&i.Address,
		&i.ProviderLocator,
		&i.Custody,
		&i.EncryptedPrivateKey,
		&i.KeyVersion,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletByID = `-- name: GetWalletByID :one
SELECT id, group_id, tenant_id, rail, chain, address, provider_locator, custody, encrypted_private_key, key_version, status, metadata, created_at, updated_at FROM wallets
WHERE id = $1 AND status <> 'deleted'
`

func (q *Queries) GetWalletByID(ctx context.Context, id string) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletByID, id)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.TenantID,
		&i.Rail,
		&i.Chain,
		&i.Address,
		&i.ProviderLocator,
		&i.Custody,
		&i.EncryptedPrivateKey,
		&i.KeyVersion,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWalletByProviderLocator = `-- name: GetWalletByProviderLocator :one
SELECT id, group_id, tenant_id, rail, chain, address, provider_locator, custody, encrypted_private_key, key_version, status, metadata, created_at, updated_at FROM wallets
WHERE rail = $1 AND provider_locator = $2 AND status = 'active'
`

type GetWalletByProviderLocatorParams struct {
	Rail            string `json:"rail"`
	ProviderLocator string `json:"provider_locator"`
}

// Reverse lookup for provider webhooks that hand us a CrossMint cm_xxx
// or similar opaque id.
func (q *Queries) GetWalletByProviderLocator(ctx context.Context, arg GetWalletByProviderLocatorParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletByProviderLocator, arg.Rail, arg.ProviderLocator)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.TenantID,
		&i.Rail,
		&i.Chain,
		&i.Address,
		&i.ProviderLocator,
		&i.Custody,
		&i.EncryptedPrivateKey,
		&i.KeyVersion,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWalletsByGroup = `-- name: ListWalletsByGroup :many
SELECT id, group_id, tenant_id, rail, chain, address, provider_locator, custody, encrypted_private_key, key_version, status, metadata, created_at, updated_at FROM wallets
WHERE group_id = $1 AND status <> 'deleted'
ORDER BY
    CASE rail
        WHEN 'crossmint' THEN 1
        WHEN 'tempo'     THEN 2
        WHEN 'loka-ln'   THEN 3
        ELSE 99
    END
`

// Returns every wallet of a group, ordered so CrossMint comes before Tempo
// before Loka-LN — gives the dashboard a stable display order without
// per-rail logic in the frontend.
func (q *Queries) ListWalletsByGroup(ctx context.Context, groupID string) ([]Wallet, error) {
	rows, err := q.db.Query(ctx, listWalletsByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Wallet{}
	for rows.Next() {
		var i Wallet
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.TenantID,
			&i.Rail,
			&i.Chain,
			&i.Address,
			&i.ProviderLocator,
			&i.Custody,
			&i.EncryptedPrivateKey,
			&i.KeyVersion,
			&i.Status,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWalletEncryptedKey = `-- name: UpdateWalletEncryptedKey :exec
UPDATE wallets
SET encrypted_private_key = $2,
    key_version = $3
WHERE id = $1 AND custody = 'platform' AND rail = 'tempo'
`

type UpdateWalletEncryptedKeyParams struct {
	ID                  string      `json:"id"`
	EncryptedPrivateKey []byte      `json:"encrypted_private_key"`
	KeyVersion          pgtype.Int2 `json:"key_version"`
}

// Used by the keystore when the master key rotates. We keep encrypted_
// private_key + key_version together to avoid ever decrypting with the
// wrong master generation.
func (q *Queries) UpdateWalletEncryptedKey(ctx context.Context, arg UpdateWalletEncryptedKeyParams) error {
	_, err := q.db.Exec(ctx, updateWalletEncryptedKey, arg.ID, arg.EncryptedPrivateKey, arg.KeyVersion)
	return err
}

const updateWalletStatus = `-- name: UpdateWalletStatus :one
UPDATE wallets
SET status = $2
WHERE id = $1
RETURNING id, group_id, tenant_id, rail, chain, address, provider_locator, custody, encrypted_private_key, key_version, status, metadata, created_at, updated_at
`

type UpdateWalletStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateWalletStatus(ctx context.Context, arg UpdateWalletStatusParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, updateWalletStatus, arg.ID, arg.Status)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.TenantID,
		&i.Rail,
		&i.Chain,
		&i.Address,
		&i.ProviderLocator,
		&i.Custody,
		&i.EncryptedPrivateKey,
		&i.KeyVersion,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
