// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_events.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhookEvent = `-- name: CreateWebhookEvent :one

INSERT INTO webhook_events (
    id, tenant_id, endpoint_id,
    event_type, event_data,
    related_wallet_id, related_group_id, related_transaction_id,
    related_onramp_order_id, related_session_key_id,
    status, attempts, next_attempt_at,
    signature_version, metadata
) VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7, $8,
    $9, $10,
    $11, $12, $13,
    $14, $15
)
RETURNING id, tenant_id, endpoint_id, event_type, event_data, related_wallet_id, related_group_id, related_transaction_id, related_onramp_order_id, related_session_key_id, status, attempts, next_attempt_at, last_response_code, last_response_body, last_error, delivered_at, signature_version, metadata, created_at, updated_at
`

type CreateWebhookEventParams struct {
	ID                   string             `json:"id"`
	TenantID             string             `json:"tenant_id"`
	EndpointID           pgtype.Text        `json:"endpoint_id"`
	EventType            string             `json:"event_type"`
	EventData            []byte             `json:"event_data"`
	RelatedWalletID      pgtype.Text        `json:"related_wallet_id"`
	RelatedGroupID       pgtype.Text        `json:"related_group_id"`
	RelatedTransactionID pgtype.Text        `json:"related_transaction_id"`
	RelatedOnrampOrderID pgtype.Text        `json:"related_onramp_order_id"`
	RelatedSessionKeyID  pgtype.Text        `json:"related_session_key_id"`
	Status               string             `json:"status"`
	Attempts             int32              `json:"attempts"`
	NextAttemptAt        pgtype.Timestamptz `json:"next_attempt_at"`
	SignatureVersion     pgtype.Int2        `json:"signature_version"`
	Metadata             []byte             `json:"metadata"`
}

// Per-(domain-event, subscribed-endpoint) delivery records. The delivery
// worker iterates pending/failed rows whose next_attempt_at has arrived.
func (q *Queries) CreateWebhookEvent(ctx context.Context, arg CreateWebhookEventParams) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, createWebhookEvent,
		arg.ID,
		arg.TenantID,
		arg.EndpointID,
		arg.EventType,
		arg.EventData,
		arg.RelatedWalletID,
		arg.RelatedGroupID,
		arg.RelatedTransactionID,
		arg.RelatedOnrampOrderID,
		arg.RelatedSessionKeyID,
		arg.Status,
		arg.Attempts,
		arg.NextAttemptAt,
		arg.SignatureVersion,
		arg.Metadata,
	)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EndpointID,
		&i.EventType,
		&i.EventData,
		&i.RelatedWalletID,
		&i.RelatedGroupID,
		&i.RelatedTransactionID,
		&i.RelatedOnrampOrderID,
		&i.RelatedSessionKeyID,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LastResponseCode,
		&i.LastResponseBody,
		&i.LastError,
		&i.DeliveredAt,
		&i.SignatureVersion,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookEventByID = `-- name: GetWebhookEventByID :one
SELECT id, tenant_id, endpoint_id, event_type, event_data, related_wallet_id, related_group_id, related_transaction_id, related_onramp_order_id, related_session_key_id, status, attempts, next_attempt_at, last_response_code, last_response_body, last_error, delivered_at, signature_version, metadata, created_at, updated_at FROM webhook_events
WHERE id = $1
`

func (q *Queries) GetWebhookEventByID(ctx context.Context, id string) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, getWebhookEventByID, id)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EndpointID,
		&i.EventType,
		&i.EventData,
		&i.RelatedWalletID,
		&i.RelatedGroupID,
		&i.RelatedTransactionID,
		&i.RelatedOnrampOrderID,
		&i.RelatedSessionKeyID,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LastResponseCode,
		&i.LastResponseBody,
		&i.LastError,
		&i.DeliveredAt,
		&i.SignatureVersion,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDueWebhookEvents = `-- name: ListDueWebhookEvents :many
SELECT id, tenant_id, endpoint_id, event_type, event_data, related_wallet_id, related_group_id, related_transaction_id, related_onramp_order_id, related_session_key_id, status, attempts, next_attempt_at, last_response_code, last_response_body, last_error, delivered_at, signature_version, metadata, created_at, updated_at FROM webhook_events
WHERE status IN ('pending', 'failed')
  AND next_attempt_at <= $1
ORDER BY next_attempt_at ASC
LIMIT $2
`

type ListDueWebhookEventsParams struct {
	NextAttemptAt pgtype.Timestamptz `json:"next_attempt_at"`
	Limit         int32              `json:"limit"`
}

// Hot path for the delivery worker. Hits the partial index on
// next_attempt_at WHERE status IN ('pending','failed'). LIMIT enforces
// per-tick budget.
func (q *Queries) ListDueWebhookEvents(ctx context.Context, arg ListDueWebhookEventsParams) ([]WebhookEvent, error) {
	rows, err := q.db.Query(ctx, listDueWebhookEvents, arg.NextAttemptAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEvent{}
	for rows.Next() {
		var i WebhookEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EndpointID,
			&i.EventType,
			&i.EventData,
			&i.RelatedWalletID,
			&i.RelatedGroupID,
			&i.RelatedTransactionID,
			&i.RelatedOnrampOrderID,
			&i.RelatedSessionKeyID,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastResponseCode,
			&i.LastResponseBody,
			&i.LastError,
			&i.DeliveredAt,
			&i.SignatureVersion,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEventsForEndpoint = `-- name: ListWebhookEventsForEndpoint :many
SELECT id, tenant_id, endpoint_id, event_type, event_data, related_wallet_id, related_group_id, related_transaction_id, related_onramp_order_id, related_session_key_id, status, attempts, next_attempt_at, last_response_code, last_response_body, last_error, delivered_at, signature_version, metadata, created_at, updated_at FROM webhook_events
WHERE endpoint_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWebhookEventsForEndpointParams struct {
	EndpointID pgtype.Text `json:"endpoint_id"`
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
}

func (q *Queries) ListWebhookEventsForEndpoint(ctx context.Context, arg ListWebhookEventsForEndpointParams) ([]WebhookEvent, error) {
	rows, err := q.db.Query(ctx, listWebhookEventsForEndpoint, arg.EndpointID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEvent{}
	for rows.Next() {
		var i WebhookEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EndpointID,
			&i.EventType,
			&i.EventData,
			&i.RelatedWalletID,
			&i.RelatedGroupID,
			&i.RelatedTransactionID,
			&i.RelatedOnrampOrderID,
			&i.RelatedSessionKeyID,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastResponseCode,
			&i.LastResponseBody,
			&i.LastError,
			&i.DeliveredAt,
			&i.SignatureVersion,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEventsForTenant = `-- name: ListWebhookEventsForTenant :many
SELECT id, tenant_id, endpoint_id, event_type, event_data, related_wallet_id, related_group_id, related_transaction_id, related_onramp_order_id, related_session_key_id, status, attempts, next_attempt_at, last_response_code, last_response_body, last_error, delivered_at, signature_version, metadata, created_at, updated_at FROM webhook_events
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWebhookEventsForTenantParams struct {
	TenantID string `json:"tenant_id"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListWebhookEventsForTenant(ctx context.Context, arg ListWebhookEventsForTenantParams) ([]WebhookEvent, error) {
	rows, err := q.db.Query(ctx, listWebhookEventsForTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEvent{}
	for rows.Next() {
		var i WebhookEvent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EndpointID,
			&i.EventType,
			&i.EventData,
			&i.RelatedWalletID,
			&i.RelatedGroupID,
			&i.RelatedTransactionID,
			&i.RelatedOnrampOrderID,
			&i.RelatedSessionKeyID,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.LastResponseCode,
			&i.LastResponseBody,
			&i.LastError,
			&i.DeliveredAt,
			&i.SignatureVersion,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markWebhookEventDead = `-- name: MarkWebhookEventDead :exec
UPDATE webhook_events
SET status = 'dead'
WHERE id = $1
`

// Terminal state after the retry budget is exhausted.
func (q *Queries) MarkWebhookEventDead(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markWebhookEventDead, id)
	return err
}

const markWebhookEventDelivered = `-- name: MarkWebhookEventDelivered :one
UPDATE webhook_events
SET status            = 'delivered',
    last_response_code = $2,
    delivered_at      = NOW()
WHERE id = $1
RETURNING id, tenant_id, endpoint_id, event_type, event_data, related_wallet_id, related_group_id, related_transaction_id, related_onramp_order_id, related_session_key_id, status, attempts, next_attempt_at, last_response_code, last_response_body, last_error, delivered_at, signature_version, metadata, created_at, updated_at
`

type MarkWebhookEventDeliveredParams struct {
	ID               string      `json:"id"`
	LastResponseCode pgtype.Int4 `json:"last_response_code"`
}

func (q *Queries) MarkWebhookEventDelivered(ctx context.Context, arg MarkWebhookEventDeliveredParams) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, markWebhookEventDelivered, arg.ID, arg.LastResponseCode)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EndpointID,
		&i.EventType,
		&i.EventData,
		&i.RelatedWalletID,
		&i.RelatedGroupID,
		&i.RelatedTransactionID,
		&i.RelatedOnrampOrderID,
		&i.RelatedSessionKeyID,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LastResponseCode,
		&i.LastResponseBody,
		&i.LastError,
		&i.DeliveredAt,
		&i.SignatureVersion,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markWebhookEventDelivering = `-- name: MarkWebhookEventDelivering :one
UPDATE webhook_events
SET status = 'delivering'
WHERE id = $1 AND status IN ('pending', 'failed')
RETURNING id, tenant_id, endpoint_id, event_type, event_data, related_wallet_id, related_group_id, related_transaction_id, related_onramp_order_id, related_session_key_id, status, attempts, next_attempt_at, last_response_code, last_response_body, last_error, delivered_at, signature_version, metadata, created_at, updated_at
`

// Take ownership: flip status to 'delivering' so a parallel worker
// doesn't pick the same row up. Returns the row only when the transition
// succeeded — concurrent workers see no rows and skip.
func (q *Queries) MarkWebhookEventDelivering(ctx context.Context, id string) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, markWebhookEventDelivering, id)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EndpointID,
		&i.EventType,
		&i.EventData,
		&i.RelatedWalletID,
		&i.RelatedGroupID,
		&i.RelatedTransactionID,
		&i.RelatedOnrampOrderID,
		&i.RelatedSessionKeyID,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LastResponseCode,
		&i.LastResponseBody,
		&i.LastError,
		&i.DeliveredAt,
		&i.SignatureVersion,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markWebhookEventFailed = `-- name: MarkWebhookEventFailed :one
UPDATE webhook_events
SET status             = 'failed',
    attempts           = attempts + 1,
    next_attempt_at    = $2,
    last_response_code = $3,
    last_response_body = $4,
    last_error         = $5
WHERE id = $1
RETURNING id, tenant_id, endpoint_id, event_type, event_data, related_wallet_id, related_group_id, related_transaction_id, related_onramp_order_id, related_session_key_id, status, attempts, next_attempt_at, last_response_code, last_response_body, last_error, delivered_at, signature_version, metadata, created_at, updated_at
`

type MarkWebhookEventFailedParams struct {
	ID               string             `json:"id"`
	NextAttemptAt    pgtype.Timestamptz `json:"next_attempt_at"`
	LastResponseCode pgtype.Int4        `json:"last_response_code"`
	LastResponseBody pgtype.Text        `json:"last_response_body"`
	LastError        pgtype.Text        `json:"last_error"`
}

// One failed delivery attempt. Bumps attempts + schedules next retry.
// The worker computes next_attempt_at via exponential backoff and
// passes it in.
func (q *Queries) MarkWebhookEventFailed(ctx context.Context, arg MarkWebhookEventFailedParams) (WebhookEvent, error) {
	row := q.db.QueryRow(ctx, markWebhookEventFailed,
		arg.ID,
		arg.NextAttemptAt,
		arg.LastResponseCode,
		arg.LastResponseBody,
		arg.LastError,
	)
	var i WebhookEvent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EndpointID,
		&i.EventType,
		&i.EventData,
		&i.RelatedWalletID,
		&i.RelatedGroupID,
		&i.RelatedTransactionID,
		&i.RelatedOnrampOrderID,
		&i.RelatedSessionKeyID,
		&i.Status,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LastResponseCode,
		&i.LastResponseBody,
		&i.LastError,
		&i.DeliveredAt,
		&i.SignatureVersion,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
