// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_endpoints.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhookEndpoint = `-- name: CreateWebhookEndpoint :one

INSERT INTO webhook_endpoints (
    id, tenant_id, url, secret, secret_version,
    subscribed_events, status, description, metadata
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9
)
RETURNING id, tenant_id, url, secret, secret_version, subscribed_events, status, description, last_success_at, last_failure_at, consecutive_failures, metadata, created_at, updated_at
`

type CreateWebhookEndpointParams struct {
	ID               string      `json:"id"`
	TenantID         string      `json:"tenant_id"`
	Url              string      `json:"url"`
	Secret           []byte      `json:"secret"`
	SecretVersion    int16       `json:"secret_version"`
	SubscribedEvents []byte      `json:"subscribed_events"`
	Status           string      `json:"status"`
	Description      pgtype.Text `json:"description"`
	Metadata         []byte      `json:"metadata"`
}

// Customer-registered webhook destinations. The HMAC secret is opaque
// bytes; the application minted it and showed it once at creation.
func (q *Queries) CreateWebhookEndpoint(ctx context.Context, arg CreateWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, createWebhookEndpoint,
		arg.ID,
		arg.TenantID,
		arg.Url,
		arg.Secret,
		arg.SecretVersion,
		arg.SubscribedEvents,
		arg.Status,
		arg.Description,
		arg.Metadata,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Url,
		&i.Secret,
		&i.SecretVersion,
		&i.SubscribedEvents,
		&i.Status,
		&i.Description,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.ConsecutiveFailures,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWebhookEndpoint = `-- name: DeleteWebhookEndpoint :exec
UPDATE webhook_endpoints
SET status = 'deleted'
WHERE id = $1 AND status <> 'deleted'
`

// Soft delete via status='deleted' so historical webhook_events still
// resolve their endpoint_id back to a row.
func (q *Queries) DeleteWebhookEndpoint(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteWebhookEndpoint, id)
	return err
}

const getWebhookEndpointByID = `-- name: GetWebhookEndpointByID :one
SELECT id, tenant_id, url, secret, secret_version, subscribed_events, status, description, last_success_at, last_failure_at, consecutive_failures, metadata, created_at, updated_at FROM webhook_endpoints
WHERE id = $1
`

func (q *Queries) GetWebhookEndpointByID(ctx context.Context, id string) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, getWebhookEndpointByID, id)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Url,
		&i.Secret,
		&i.SecretVersion,
		&i.SubscribedEvents,
		&i.Status,
		&i.Description,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.ConsecutiveFailures,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveEndpointsForTenant = `-- name: ListActiveEndpointsForTenant :many
SELECT id, tenant_id, url, secret, secret_version, subscribed_events, status, description, last_success_at, last_failure_at, consecutive_failures, metadata, created_at, updated_at FROM webhook_endpoints
WHERE tenant_id = $1 AND status = 'active'
`

// The publisher fans out one domain event to every active subscriber of
// this tenant. Filtering on subscribed_events happens in app code (JSONB
// containment) so each event is matched against the array.
func (q *Queries) ListActiveEndpointsForTenant(ctx context.Context, tenantID string) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, listActiveEndpointsForTenant, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEndpoint{}
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Url,
			&i.Secret,
			&i.SecretVersion,
			&i.SubscribedEvents,
			&i.Status,
			&i.Description,
			&i.LastSuccessAt,
			&i.LastFailureAt,
			&i.ConsecutiveFailures,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhookEndpointsForTenant = `-- name: ListWebhookEndpointsForTenant :many
SELECT id, tenant_id, url, secret, secret_version, subscribed_events, status, description, last_success_at, last_failure_at, consecutive_failures, metadata, created_at, updated_at FROM webhook_endpoints
WHERE tenant_id = $1 AND status <> 'deleted'
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWebhookEndpointsForTenantParams struct {
	TenantID string `json:"tenant_id"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

func (q *Queries) ListWebhookEndpointsForTenant(ctx context.Context, arg ListWebhookEndpointsForTenantParams) ([]WebhookEndpoint, error) {
	rows, err := q.db.Query(ctx, listWebhookEndpointsForTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookEndpoint{}
	for rows.Next() {
		var i WebhookEndpoint
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Url,
			&i.Secret,
			&i.SecretVersion,
			&i.SubscribedEvents,
			&i.Status,
			&i.Description,
			&i.LastSuccessAt,
			&i.LastFailureAt,
			&i.ConsecutiveFailures,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pauseWebhookEndpoint = `-- name: PauseWebhookEndpoint :exec
UPDATE webhook_endpoints
SET status = 'paused'
WHERE id = $1 AND status = 'active'
`

func (q *Queries) PauseWebhookEndpoint(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, pauseWebhookEndpoint, id)
	return err
}

const rotateWebhookEndpointSecret = `-- name: RotateWebhookEndpointSecret :one
UPDATE webhook_endpoints
SET secret         = $2,
    secret_version = secret_version + 1
WHERE id = $1
RETURNING id, tenant_id, url, secret, secret_version, subscribed_events, status, description, last_success_at, last_failure_at, consecutive_failures, metadata, created_at, updated_at
`

type RotateWebhookEndpointSecretParams struct {
	ID     string `json:"id"`
	Secret []byte `json:"secret"`
}

// Bumps the secret and its version atomically. Deliveries already in
// flight keep using the prior version via webhook_events.signature_version.
func (q *Queries) RotateWebhookEndpointSecret(ctx context.Context, arg RotateWebhookEndpointSecretParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, rotateWebhookEndpointSecret, arg.ID, arg.Secret)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Url,
		&i.Secret,
		&i.SecretVersion,
		&i.SubscribedEvents,
		&i.Status,
		&i.Description,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.ConsecutiveFailures,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchWebhookEndpointFailure = `-- name: TouchWebhookEndpointFailure :one
UPDATE webhook_endpoints
SET last_failure_at      = NOW(),
    consecutive_failures = consecutive_failures + 1
WHERE id = $1
RETURNING consecutive_failures
`

// Bumps the failure counter and returns the new value so the worker can
// decide whether to auto-pause the endpoint (e.g. after 30 in a row).
func (q *Queries) TouchWebhookEndpointFailure(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRow(ctx, touchWebhookEndpointFailure, id)
	var consecutive_failures int32
	err := row.Scan(&consecutive_failures)
	return consecutive_failures, err
}

const touchWebhookEndpointSuccess = `-- name: TouchWebhookEndpointSuccess :exec
UPDATE webhook_endpoints
SET last_success_at      = NOW(),
    consecutive_failures = 0
WHERE id = $1
`

func (q *Queries) TouchWebhookEndpointSuccess(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchWebhookEndpointSuccess, id)
	return err
}

const updateWebhookEndpoint = `-- name: UpdateWebhookEndpoint :one
UPDATE webhook_endpoints
SET url               = COALESCE($2, url),
    subscribed_events = COALESCE($3, subscribed_events),
    description       = COALESCE($4, description),
    status            = COALESCE($5, status)
WHERE id = $1
RETURNING id, tenant_id, url, secret, secret_version, subscribed_events, status, description, last_success_at, last_failure_at, consecutive_failures, metadata, created_at, updated_at
`

type UpdateWebhookEndpointParams struct {
	ID               string      `json:"id"`
	Url              string      `json:"url"`
	SubscribedEvents []byte      `json:"subscribed_events"`
	Description      pgtype.Text `json:"description"`
	Status           string      `json:"status"`
}

// Mutable surface: URL, subscribed_events, description, status. The
// secret is rotated via RotateWebhookEndpointSecret only — keeping the
// updates separate so a tenant can't accidentally race a URL change with
// a secret rotation in the same call.
func (q *Queries) UpdateWebhookEndpoint(ctx context.Context, arg UpdateWebhookEndpointParams) (WebhookEndpoint, error) {
	row := q.db.QueryRow(ctx, updateWebhookEndpoint,
		arg.ID,
		arg.Url,
		arg.SubscribedEvents,
		arg.Description,
		arg.Status,
	)
	var i WebhookEndpoint
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Url,
		&i.Secret,
		&i.SecretVersion,
		&i.SubscribedEvents,
		&i.Status,
		&i.Description,
		&i.LastSuccessAt,
		&i.LastFailureAt,
		&i.ConsecutiveFailures,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
